### ISSUE TITLE
Feature request: possibility to generate compile_commands.json

### ISSUE THREAD

**Issue by rapgenic** [microsoft/vscode-makefile-tools#104]
The [compile_commands.json](https://clang.llvm.org/docs/JSONCompilationDatabase.html) file is quite useful for many tools in the C/C++ ecosystem, and given that the extension already collects all the required information it should be easy to write down that file on configuration completed.

This would also allow to get rid of other software like bear or compiledb, that are used to generate such file, which might be tricky to install.

I am working on the code right now, and I already have a working proof of concept; if you are interested I can open a pull request for you to review the code (it's a quite simple modification)

**Comment by andreeis** [comment]
Thank you for the feature idea and for willing to help us implement it. Indeed this would be a very useful functionality.
We are interested in reviewing and testing a PR from you. We would merge it in after we ship Makefile Tools on the MS Market Place next week. You and any other developers in the community will be able to use it immediately even if it won't be included in our first public release because we can build a VSIX after every PR is completed.
Looking forward to see your code and incorporate it in the extension.

**Comment by andreeis** [comment]
@rapgenic, we released Makefile Tools 0.3.0 today which includes this feature you implemented for us. Thank you very much for your contribution. Let us know if you encounter any other issues.

If you are happy with the extension, you can leave us a review on [Market Place](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools&ssr=false#review-details).
