### ISSUE TITLE
Makefile target is not listed

### ISSUE THREAD

**Issue by simonsunnyboy** [microsoft/vscode-makefile-tools#116]
My project only outputs a listing of possible targets.
The current plugin does not detect those options on its own.
What i need is "make x" instead of "make all" or "make all x"

I tried the configurations but this only executes "make all x"
    "makefile.configurations": [
        {
            "name": "x",
            "makeArgs": ["x"]
        }
    ],

I would be totally fine if the "Set the target to be built by make" would accept a free text and wouldn't limit the user to autodetected choices.

**Comment by andreeis** [comment]
Thank you for opening this report. We are sorry you experience this inconvenience and we will address this as soon as possible.
Please attach the .vscode/targets.log and point us where the un-detected target is.
And yes, as a workaround for exactly these situations we will make the target editable and/or offer a setting.

**Comment by andreeis** [comment]
A workaround now, for having make X instead of make all X, keep the configurations as you defined them, they will ensure the X but to get rid of all don't set all as a target (which you probably did in the left side panel UI (right?). Currently, we don't have a way to unset a target back to the empty default (we have a work item for this too) but you can reset the whole state of the project with this command "Makefile: Reset the Makefile Tools Extension workspace state (for troubleshooting)".

Let us know if you still get 'all' if you do the above. You can see the exact make command that the extension invokes in the output channel.

**Comment by simonsunnyboy** [comment]
Project is EmuTOS, https://emutos.sourceforge.io/

Targets not listed are:
$ make all
Please read doc/install.txt before continuation.

target  meaning
------  -------
help    this help message
version display the EmuTOS version
192     etos192us.img, EmuTOS ROM padded to size 192 KB
256     etos256us.img, EmuTOS ROM padded to size 256 KB
512     etos512k.img, EmuTOS ROM padded to size 512 KB
aranym  emutos-aranym.img, suitable for ARAnyM
firebee emutosfb.s19, to be flashed on the FireBee
firebee-prg emutos.prg, a RAM tos for the FireBee
amiga   emutos-amiga.rom, EmuTOS ROM for Amiga hardware
amigavampire emutos-vampire.rom, EmuTOS ROM for Amiga optimized for Vampire V2
v4sa    emutos-vampire-v4sa.rom, EmuTOS ROM for Amiga Vampire V4 Standalone
amigakd emutos-kickdisk.adf, EmuTOS as Amiga 1000 Kickstart disk
amigaflop emutos.adf, EmuTOS RAM as Amiga boot floppy
amigaflopvampire emutos-vampire.adf, EmuTOS RAM as Amiga boot floppy optimized for Vampire V2
m548x-dbug emutos-m548x-dbug.s19, EmuTOS-RAM for dBUG on ColdFire Evaluation Boards
m548x-bas  emutos-m548x-bas.s19, EmuTOS for BaS_gcc on ColdFire Evaluation Boards
m548x-prg  emutos.prg, a RAM tos for ColdFire Evaluation Boards with BaS_gcc
prg     emutos.prg, a RAM tos
flop    emutosus.st, a bootable floppy with RAM tos
pak3    etospak3us.img, suitable for PAK/3 systems
all192  all 192 KB images
all256  all 256 KB images
allpak3 all PAK/3 images
allprg  all emutos*.prg
allflop all emutos*.st
cart    etoscart.img, EmuTOS as a diagnostic cartridge
clean
expand  expand tabs to spaces
crlf    convert all end of lines to LF
charset check the charset of all the source files
bugready set up files in preparation for 'bug update'
gitready same as make expand crlf
dsm     dsm.txt, an edited disassembly of emutos.img
release build the release archives into release-archives

targets.log is attached
[targets.log](https://github.com/microsoft/vscode-makefile-tools/files/6016037/targets.log)

**Comment by simonsunnyboy** [comment]
I only have "all" as a target on the left panel and no other choices, regardless of "configurations" provided.

![image](https://user-images.githubusercontent.com/11463542/108605587-34615180-73b5-11eb-8bda-db71b9c1da25.png)

**Comment by andreeis** [comment]
If you run the command "Makefile: Reset the Makefile Tools Extension workspace state (for troubleshooting)", the "all" will be replaced with empty. "all" will not be sent to any of our "make" invocations. This will allow only the "makeArgs" you set in the "prg" configuration to be included in the "make" command.
You are saying that's not the case? The resetting command did not 'wipe out' the 'all' in the UI?

And then I am confused by your previous reply, when you copy paste EmuTOS details. Not sure how that is relevant to our investigation (or was it help for us to clone and setup the repository?). Then you write: "Targets not listed are: $ make all", as if you actually want "all" and it's missing.

In the mean time, I will investigate whether "prg" target is missing (I hope I guessed correctly which one to focus on), if it's missing we'll fix the detection for the soon upcoming patch release 0.2.1. 

I was thinking to add a setting (string, or string array) for additional targets, to be used especially when the parser is not detecting some of them. But then I realized we have the makefile.configurations[].makeArgs and I'm not sure wet need anything else. You are the perfect user to let us know whether this existing setting (makefile.configurations[].makeArgs) is not enough for when the extension fails to parse all the targets and if we would need an additional one let's say "makefile.additionalTargets".

The editing of the quickPick UI element (that would be a different mechanism to hook up un-identified targets) will be triaged for a later major release. But the above argument (makeArgs) applies to this as well. Let us know why you think we would need this UI change.

Summary: is "makefile.configurations[].makeArgs" not enough to hook (temporarily until we fix the parser) any missing targets?

**Comment by simonsunnyboy** [comment]
No makeArgs is what I tried initially. It appends target "all" so when I run the prg target, it actually performs

$ make all prg

when the following snippet is part of settings.json

"makefile.configurations": [
{
"name": "prg",
"makeArgs": ["prg"]
}
],

In this project case this actually works but there may be others where "all" really does all and not the intended part.

considering 
"And then I am confused by your previous reply, when you copy paste EmuTOS details. Not sure how that is relevant to our investigation (or was it help for us to clone and setup the repository?). Then you write: "Targets not listed are: $ make all", as if you actually want "all" and it's missing."

It is the opposite. "all" is a helper target here for use on the console which then lists the possible actual targets such as all192 or  all256. The plugin seems not to detect those individual actual targets as available from the Makefile.

**Comment by andreeis** [comment]
Ok, I know what's going on.

The extension doesn't parse any build targets because we do not support yet localization in this extension. There are some strategic string searches in .vscode/targets.log which currently work for english only. I didn't realize that, we would have written about it. Localization will be achieved in some of our future releases.

But still, if you insert any missing target via "makeArgs", even if in the UI you would have empty or 'all' as a build target, the IntelliSense and build features should work. The "make --dry-run" invocation we do for IntelliSense and the "make" invocation we do for building, does not append "all". Indeed, when we invoke "make" to parse for available targets, we automatically append "all" (I can explain why, if needed), so now I understand why you kept complaining you couldn't get rid of "all". But that was only from the "make" command for parsing build targets (which you see last in the output channel), not for when using "make" to parse IntelliSense or when doing a real build of target "prg".

If you ignore that you see "all" or empty (if you ran the "troubleshooting" command) in the "build targets" in the side panel UI, anything else not working for you?
Actually, it's possible IntelliSense may not work properly since when parsing for that we also use some english keywords. Especially around folders/directories (but if your project is simple and stays in one place it shouldn't be affected).

To overcome the localization problem, can you use make with english for now, as a workaround? That should get your build targets quickPick populated. Let us know if that's not the case.

Also, I heard there could be ways to invoke make with english on non english systems. I never tried and I briefly read about LANG and other LC_* environment variables. If you manage to get that concept working, you can hook these environment variables to the extension, so that you keep using "make" with non english but our extension uses it with english. You can hook environment variables by setting them in a script, pointing the setting "makefile.preConfigureScript" to that file and then running the script via the command "makefile.preconfigure". All make invocations from the extension will use english and won't bother you, since the extension will consume the output.

**Comment by simonsunnyboy** [comment]
Are you referring to the localisation used by make itself?
So it fails due to my make reporting German text.

I can understand that and will try to make it use English.

I tried on a local console only but not yet within Visual Studio Code:

`$ make tfred`
`make: *** Keine Regel, um „tfred“ zu erstellen.  Schluss.`
`$ LANGUAGE=en_US make trffef`
`make: *** No rule to make target 'trffef'.  Stop.`

**Comment by andreeis** [comment]
Oh you made it work, cool. Thanks, that example will help us incorporate the trick in the extension automatically, even for when we'll have implemented localization. The messages the extension reports to the user will always need to be localized, but output from make, gcc and other tools it will be good to be produced always in english regardless since just the extension consumes (or the user during investigations but I'm sure that's not an issue for anyone). Your experiment proves it's possible, thank you.

**Comment by simonsunnyboy** [comment]
I also managed to reroute the tool through a shell script now. I had to set the Make Path with an absolute path to my wrapper script.

Now the additional build targets are found correctly.

This is a temporary workaround for my needs. 

Thank you for your patience :)

**Comment by simonsunnyboy** [comment]
Closed as an additional more precise issue was opened.

**Comment by andreeis** [comment]
Oh, that was a cool idea. Simpler than introducing a pre-Configure step in your workflow. I'm sure we'll steal it :). 
Why do you say temporary? What isn't fully working with this setup? Just asking to make sure we don't overlook anything when addressing this issue.
If the extension were to always add that prefix ("LANGUAGE=en_US ") before any make invocations that we do for configure and targets (except for the build operation, which we don't read from, it's only for the user's convenience) would you be satisfied?

**Comment by simonsunnyboy** [comment]
If it it solves the problem, yes ofcourse.
I noticed I couldn't get it to work with the makePath itself which is why I rerouted make.

**Comment by andreeis** [comment]
@simonsunnyboy, is it handy for you to try the same trick for windows and let us know what adaptations are needed? Otherwise I'll experiment with this sometimes soon, no worries.

**Comment by simonsunnyboy** [comment]
I'll have to check as I normally don't use Windows for development. This will take some time for me to install tools un my Windows machine.

**Comment by andreeis** [comment]
@simonsunnyboy, I forgot to update you. There is no need to experiment anymore. We figured out over here. Thank you for letting me know before you would have spent the time.
