### ISSUE TITLE
makefile could not find another included makefile

### ISSUE THREAD

**Issue by d-chris** [microsoft/vscode-makefile-tools#117]
my `makefile` includes another `make.target` which  contains some additional variables

```make 
include make.target
```

the `makefile` and `make.target` is not the `${workspaceFolder}` but in the same directory. i specified the path to the makefile within the settings.json

```json
"makefile.makefilePath": "./cavr/adif/makefile"
```

an ugly workaround is to copy `make.target` into the `${workspaceFolder}` a better solution could be

```
"makefile.makefile" : {
   "makefile" : "makefile"
   "makepath" : "./cavr/adif/" 
}
```

**Comment by andreeis** [comment]
You need the argument -C to be included in the "make" invocation command. You can achieve this by defining a makefile configuration:

"makefile.configurations": [
    "name": "MyConfiguration",
    "makeArgs": "-C ./cavr/adif/",
    "makefilePath": "./cavr/adif/makefile"   --> the top level setting "makefilePath" works as well, it will be applied, but defining it here is an alternative
]

I think we would rather add a "makefile.runFromDirectory" (or some other name) at the project level and an equivalent one "makefile.configurations[].runFromDirectory" for each makefile configuration (if the user defines one).

While we brainstorm about how to better support this scenario, try the workaround above with "makeArgs" passing "-C" to "make". At some point we had the extension add automatically -C and the path of "makefilePath" but we later found repositories that had issues with that and we backed out the change. It all depends on the makefiles are written, what kind of paths they use when they reference dependencies. Sometimes -C is needed, sometimes not.

**Comment by nchevsky** [comment]
@andreeis

> You need the argument -C to be included in the "make" invocation command. You can achieve this by defining a makefile configuration:
> 
> ```
> "makefile.configurations": [
>   "name": "MyConfiguration",
>   "makeArgs": "-C ./cavr/adif/",
>   "makefilePath": "./cavr/adif/Makefile"
> ]
>```

This doesn't work because (Cygwin) `make` first changes into the `-C` directory and then treats `makefilePath` as relative to that directory, which ultimately resolves to `./cavr/adif/cavr/adif/Makefile` ❌:

```
make.exe -C ./cavr/adif/ -f ./cavr/adif/Makefile
make: Entering directory './cavr/adif/'
make: cavr/adif/Makefile: No such file or directory
```

This is a 🐔-and-🥚 problem:

- If we specify both `-C` and `makefilePath`, `vscode-makefile-tools` can find the Makefile but `make` can't.
- If we omit `-C` and specify `makefilePath`, `vscode-makefile-tools` and `make` can both find the Makefile, but `make` breaks when the Makefile contains relative paths.
- If we specify `-C` and omit `makefilePath`, `make` works but `vscode-makefile-tools` can't find the Makefile.

At the moment, the only reasonably simple way to work around this is to give `makefilePath` an absolute path 🤢:

```
"makefile.configurations": [
  "name": "MyConfiguration",
  "makeArgs": "-C ./cavr/adif/",
  "makefilePath": "C:/Nasty/Absolute/Path/cavr/adif/Makefile" 🤢
 ]
```

This results in `make` being called as...

`make.exe -C ./cavr/adif/ -f C:/Nasty/Absolute/Path/cavr/adif/makefile`

... which is gross but allows `make` to find the Makefile after `cd`ing into `./cavr/adif/`.

> I think we would rather add a "makefile.runFromDirectory" (or some other name) at the project level and an equivalent one "makefile.configurations[].runFromDirectory" for each makefile configuration (if the user defines one).

👍🏻 May I suggest `basePath` or `workingPath`, and having `vscode-makefile-tools` look for the Makefile in there as well (unless `makefilePath` is also set) so that we don't have to specify the same path in multiple arguments?

**Comment by andreeis** [comment]
Good idea for bullet 3: to have the extension find the makefile if -C is in the command. We'll fix this.

**Comment by nchevsky** [comment]
> Good idea for bullet 3: to have the extension find the makefile if -C is in the command. We'll fix this.

Thank you! When matching, please note `-C` also has a long form, `--directory=`.

**Comment by andreeis** [comment]
@d-chris and @nchevsky, you can try a vsix from here (https://github.com/microsoft/vscode-makefile-tools/actions/runs/814645166) to see if we fixed these situations right.

You can define now "makefile.makeDirectory" globally or under a configuration "makefile.configurations[].makeDirectory". Without defining "makefilePath" and wihout having a makefile at the workspace root, the extension will search for the makefile at the location pointed to by makeDirectory. Let us know if this doesn't fix it all for your repository scenario.

**Comment by nchevsky** [comment]
> @d-chris and @nchevsky, you can try a vsix from here (https://github.com/microsoft/vscode-makefile-tools/actions/runs/814645166) to see if we fixed these situations right.
> 
> You can define now "makefile.makeDirectory" globally or under a configuration "makefile.configurations[].makeDirectory". Without defining "makefilePath" and wihout having a makefile at the workspace root, the extension will search for the makefile at the location pointed to by makeDirectory. Let us know if this doesn't fix it all for your repository scenario.

Works great! With only `makeDirectory` set (i.e. no `makeArgs` or `makefilePath`), the extension automatically passes `-C` (and no `-f`) to `make`, both `make` and the extension can find the Makefile, and `make` can follow paths relative to `makeDirectory`. Thank you for the quick fix!
