### ISSUE TITLE
Generate compile_commands.json for Makefile projects

### ISSUE THREAD

**Issue by mgerhardy** [microsoft/vscode-makefile-tools#124]
There is e.g. compiledb available: https://pypi.org/project/compiledb/ 

It would be very cool to include this or something like this in order to use clangd language server and or the ms intellisense working properly.

**Comment by bobbrow** [comment]
Thanks for the suggestion.  I don't think we can use that project directly because the license isn't fully compatible with ours (we'd have to ask our legal team), but the suggestion to write a compile_commands.json file is still a reasonable one and we should already have the data we need.

This extension's intent is to interface directly with the C++ extension such that compile_commands.json is not needed for IntelliSense.  If that is not working for you, we'd like to know so that we can help you get past that issue.

**Comment by andreeis** [comment]
There is also a PR from the community implementing compile_commands.json support in Makefile Tools extension. We will not include that in our next patch release 0.2.1 but soon after that (possibly 0.3.0).
Anyway, it would be very valuable if you help us reproduce the IntelliSense problems you are seeing so that we fix them. Make sure you select Makefile Tools as IntelliSense configuration provider.
"C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools",
