### ISSUE TITLE
Do not append .exe to command

### ISSUE THREAD

**Issue by Marsfan** [microsoft/vscode-makefile-tools#134]
I primarily use makefiles though WSL. Because of this, the way I run `make` is with the following command

```powershell
wsl -e make
```

When I configure the makePath as 
```JSON
 `"makefile.makePath": "wsl -e make",`
```
The extension then adds the the extension `.exe` to the end of the command. This results in the following error in the _Makefile Tools_ output window:

```powershell
'"wsl -e make.exe"' is not recognized as an internal or external command,
```

**Comment by andreeis** [comment]
Thank you for opening this report. We will fix this for the soon upcoming patch release.
The problem is that we thought of makePath as path, not as a command but we understand your scenario and we'll think what to do about it.

As a workaround, make yourself a full clean build log by running any commands you need in your terminal, point that output to the extension via the setting "makefile.buildLog". This will avoid invoking "make" for setting up IntelliSense in your code base.

Then, the targets detection will fail because even if "makefile.buildLog" is used, we still invoke a particular "make" command to produce a special ouput from which we parse targets. But "all" is always included. If you need any other target than "all", define a configuration with "makeArgs" in "makefile.configurations" and pass the desired target as an argument to make.

And then of course the build feature will not work but you can run that from the terminal.
Debug/Run should work fine despite this.

We hope you can still use this extension until we release a fix.

**Comment by bobbrow** [comment]
Have you tried using the [Remote - WSL extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) in VS Code to do your WSL work?  This will launch the extension in linux mode which wouldn't require prepending `wsl -e` to your make command.

Since the release of that extension, the C/C++ extension no longer supports IntelliSense for WSL when running the Windows version of the extension.  (it may still work, but there are no guarantees)

**Comment by andreeis** [comment]
Implementing the possibility to prefix the make invocation command will be addressed later (https://github.com/microsoft/vscode-makefile-tools/issues/152). The 0.2.1 for this GitHub issue will be just being more clever when adding the ".exe" extension on windows. There was some wrong logic around that. PR coming soon.
This fix may also enable you to use a wrapper script (define "makefile.makePath": "./wrapperMake.bat") (which is still a hack but better maybe) which can run a command like "wsl -e make %*" (%* is to pass any arguments given by the extension to "makefile.makePath" forward towards the real make.

**Comment by andreeis** [comment]
You can test a vsix from here: https://github.com/microsoft/vscode-makefile-tools/actions/runs/794271000, until we release 0.2.1.
