### ISSUE TITLE
cannot select target in the tag:build target

### ISSUE THREAD

**Issue by SPRINGING** [microsoft/vscode-makefile-tools#141]
I am trying to build MFEM: https://github.com/mfem/mfem using vscode. The makefile in the project support target for debug, parallel, etc. I am able to build them through terminal. In the makefile-tools, the only target I can select is [all].  Can I change it through configuring the setting.json?

**Comment by andreeis** [comment]
I quickly cloned the mentioned repo (always the easiest to share your projects with us) and I am seeing 227 build targets being identified.

We would like to replicate your scenario exactly over here. Can you share with us more commands that you are using in your terminal?

Also, we'd like to have a look at these files that the extension works with:
- .vscode/dryrun.log
- .vscode/extension.log (after you set "makefile.extensionLog": ".vscode/extension.log" and you reload your project)
- .vscode/settings.json (if you defined anything interesting over there, otherwise no need)

**Comment by SPRINGING** [comment]
Thanks very much for your answer. I added an argument 'config' in setting.  Here is my setting for the 3 files:

- .vscode/dryrun.log

`make all config -f /home/bbnc_zak/zak_BBNC/Projects/finiteElementAnalysis/mfem/makefile --dry-run --keep-going --print-directory
make: enter directory “/home/bbnc_zak/zak_BBNC/Projects/finiteElementAnalysis/mfem”
 
/home/bbnc_zak/zak_BBNC/Projects/finiteElementAnalysis/mfem/makefile:179: *** Target 'config' can not be combined with other targets。 stop。
 
make: leave directory“/home/bbnc_zak/zak_BBNC/Projects/finiteElementAnalysis/mfem”`

- .vscode/extension.log


`Writing extension log at /home/bbnc_zak/zak_BBNC/Projects/finiteElementAnalysis/mfem/.vscode/extension.log
Saving opened files before build.
Building the current target. Command: make all config -f /home/bbnc_zak/zak_BBNC/Projects/finiteElementAnalysis/mfem/makefile
/home/bbnc_zak/zak_BBNC/Projects/finiteElementAnalysis/mfem/makefile:179: *** Target 'config' can not be combined with other targets。 停止。
Target all failed to build.
`
- .vscode/settings.json

`{
    "makefile.extensionOutputFolder": "./.vscode",
    "makefile.configurations": [
        {
            "name": "littlekernel",
            "makeArgs": ["config"]
        }
    ]
}`


sincerely,

**Comment by andreeis** [comment]
There is currently no way to unselect a build target (or any item in the left side panel UI), we have a work item for that: .
But if you run the command "Makefile: reset the Makefile Tools Extension workspace state (For troubleshooting)" from the palette, you will unset the makefile configuration, the build target and the launch target.
You will have to reset your makefile configuration (which is "config") and then there should be no "all" passed when building or when dry-run-ing for IntelliSense. The "all" I see in your command must be present because you previously selected the "all" target in the UI? We don't automatically add it to the make command (unless I'm not aware of some other bug).

Let me know how it goes after you run the reset state command and in the meantime I'll address the other issues.
