### ISSUE TITLE
launchConfigurations are sometimes duplicated

### ISSUE THREAD

**Issue by hitman-codehq** [microsoft/vscode-makefile-tools#146]
Hello plugin developers!

I have attached a .vscode\settings.json file that I use for cross development using the makefile plugin (as a .zip file as .json is not a supported upload format).  This settings.json file is configured to allow me to remotely execute the software I have built.

It works well *but* there is sometimes some strange behaviour of the plugin.  If you select the Makefile plugin icon on the left of VS Code and then click the "Change launch configuration" button next to "Launch target" then you should see something like the following in the dropdown (paths probably altered for your system):

\cygdrive\d\Source\WRC\Debug>WRC.debug()
d:\Source\WRC>..\..\Utils\Windows\RADRunner.exe(vampire,script,..\SendAndExecute.rad)

So first, I have no idea what that first \cygdrive line is because it's not in my configuration and I'm not using Cywin (although the cross compiler I am using is based on Cygwin but I never told the plugin that).  What is that exactly?  Selecting it adds an unusable entry to my settings.json file.

The second line, starting with d:\Source... works for me.  However, let's say I want to edit it.  I want to add a parameter to the binaryArgs array for instance.  If I then select the dropdown again then it will display the two entries shown above *and* a new entry representing the target that contains the new parameter.  The old entry shouldn't be present as it doesn't exist any more.

What is more unusual is that if I select the old entry in the dropdown list, it is *recreated* in my settings.json file!

This might seem like a mild annoyance (and I am guessing you might even reply with "It's designed to work like that") but it becomes much more than a mild annoyance when you are making lots of changes to the settings.json file to try to get it working.  Because every change results in a new entry appearing in the dropdown menu and because they all look very similar (or sometimes even the same) it is hard to know which entry actually represents the most recent edit of the settings.json file.

End the end I end up having to quit VS Code and then restart it so that there is only one entry in the dropdown representing the latest "version" of my launch configuration!

It would be very nice if we could fix this, and possibly address the mystery \cygdrive launch target.

[settings.zip](https://github.com/microsoft/vscode-makefile-tools/files/6330922/settings.zip)

**Comment by andreeis** [comment]
I agree that the launch targets symptom that you described can easily become annoying. We have several other similar bugs identified in this area that we were planning to address after 0.2.1 but let me see if I can easily fix this particular scenario for the upcoming 0.2.1.

The mystery with cygdrive comes from the fact that the extension detects if your VSCode instance was launched from a cygwin or msys or mingw environment (do you confirm?) and every time we construct a full path it calls for the "cygpath" tool, with -w argument. This was the only solution we found to be able to get the real path on windows when posix tools (like make, gcc, ...) would report posix paths within the drive that is set as "home" for these environments. Something is wrong in our path processing, let's find out. Can you share a configure log with "makefile.loggingLevel" set to "Debug" or your project (and instructions how you open/load it).

**Comment by andreeis** [comment]
The following work item will add readable names (also editable by you) to each different and slightly similar configuration: https://github.com/microsoft/vscode-makefile-tools/issues/121.
Until then, also note that the "mouse over" event on the launch configuration node will show CWD+Binary+Args of the currently set launch configuration which will help you a bit to differentiate between all of them now.

The following work item will address the problem of regular cleanup of stale launch configurations: https://github.com/microsoft/vscode-makefile-tools/issues/155. 

The current work item is tracking the fact that once you have a launch configuration selected in the UI and you edit in settings.json it will not be updated in the UI.

And now more details that will hopefully clarify what/why happens.
**Launch targets:** 
- a binary that is detected by the extension while parsing the make logs. It contains: cwd, binary full path and arguments.
- every linker command (of executable) produces one launch target with 0 array of args.
- every makefile target that invokes (runs) a binary that we know was built during the build process (so not any random binary) it becomes a launch target with cwd, full path and any args that the makefile defines.
- launch targets are detected during the configure process. If configure doesn't run, there are no launch targets.
- all launch targets that are being parsed are included in the quick pick that you open when pressing "launch configuration" on the left side UI

**Launch configurations:**
- a launch configuration is based on a launch target and the user can edit stuff (like args) or add new information (stopOnEntry, miMode, symbols path, ...etc...)
- currently without a unique name for launch configurations, they can be differentiated only by the combination of cwd+path+args, so watch out there (avoid defining 2 identical cwd+path+args with different debugger attributes). Work item 121 will solve this.
- launch configurations also populate the quick pick (same as launch targets)
- a change of args to an existing launch configuration makes sense to result in a different entry
- the bug here is what to do with the old launch configuration (before the edit). If the old one is perfect match with one launch target it should remain, you should be able to click it again in future. But if it doesn't match anything that can rely exclusively on makefile logs parsing then we should delete it (and we don't now). Fixing this will reduce a bit the launch configurations pollution in the settings but not completely. If the user manually goes through many launch targets and for each it defines all sorts of variations, the extension cannot clean them up without the user supervision. Work item 155 will help in future to remove stale configurations but in the end perfect cleanup will have to be done by the user.

Also, if you find yourself that you need to unset the launch configuration (we have a different work item to have that possible through the UI, currently once you set it you can't unset it, only change it to something else https://github.com/microsoft/vscode-makefile-tools/issues/125) you can run the command "Makefile: Reset set for troubleshooting" from the palette (which will reset build target and makefile configuration as well, but it's easy to set them back).

**Comment by andreeis** [comment]
When a launch configuration entry is manually edited in .vscode/settings.json and it happens to be the current launch configuration selected previously for the project, if the manual edit results in changing the identity of the entry (cwd+bin+args, as opposed to the other fields like stopAtEntry or miMode...etc...) then it is treated as a new launch configuration (there will be a new entry in the quick pick) but the current launch configuration is seen as not found and it gets unset (as opposed to being updated with info from the manual edit, that was more complicated to fix now for 0.2.1). Before this fix, the current launch configuration remained the old one, it was invalid, leading to all sorts of minor bugs in time. Also I fixed other similar not too critical but very confusing bugs regarding launch targets and configurations. PR will be out soon and I'll be able to give you a vsix to try so that you benefit of this cleanup before we release 0.2.1 (few days away).

**Comment by andreeis** [comment]
We fixed this issue and until we release 0.2.1 you can try, if you want, a vsix from here (https://github.com/microsoft/vscode-makefile-tools/actions/runs/814645166).
