### ISSUE TITLE
Warnings are not displayed in the "Problems" tab

### ISSUE THREAD

**Issue by hitman-codehq** [microsoft/vscode-makefile-tools#147]
Please find attached two files:

Warnings.zip, which contains a simple test.cpp file and a makefile.
NoWarnings.png, which shows what happens when I build the test using VS Code and the makefile plugin.

You can see from the NoWarnings.png screenshot that I have designed the example to cause a compiler warning to be emitted.  However, the compiler warning is not being added to the "problems" tab.  For my daily development I use both CMake and make to build my project, and I thought it might be some interaction with these two build systems that was causing this.  So I made this simple makefile only example and it is showing the problem, so that proves that it is not something to do with using multiple build systems.

The strange thing is that *sometimes* the warnings get picked up by the makefile plugin.  Or maybe I might be imagining that.  :-)

To reproduce the issue, simply unzip the Warnings.zip file to a directory, import it into VS Code and build using the makefile plugin.  I am using MinGW GCC to compile.

![NoWarnings](https://user-images.githubusercontent.com/29058809/115141730-386cc100-a03e-11eb-80b9-d542d039958d.png)
[Warnings.zip](https://github.com/microsoft/vscode-makefile-tools/files/6330920/Warnings.zip)

**Comment by andreeis** [comment]
We don't have yet support for problem matchers. We plan to address this limitation post 0.2.1. We are tracking this with https://github.com/microsoft/vscode-makefile-tools/issues/7 so I will close this report as a duplicate.
Also, you are not imagining that sometimes you do see problems (errors/warnings). Those are not detected by Makefile Tools. Either by CMake Tools when it's also activated or by CppTools (which runs the IntelliSense compiler in the background) like in the case of makefile only project that you shared.
Thank you for your patience while we fix bugs and implement new features in the Makefile Tools extension.

**Comment by hitman-codehq** [comment]
Thanks for taking the time to respond @andreeis.  The makefile plugin is still a new product so no worries at all if there is the occasional problem.  Bring on 0.2.1!  :-)

**Comment by andreeis** [comment]
@hitman-codehq, building a target with Makefile Tools will have problem matchers support in the 0.3 release so you will be able to see errors/warnings in the Problems tab without a tasks.json workaround. While we wrap-up the release, you can test a vsix from [this link](https://github.com/microsoft/vscode-makefile-tools/actions/runs/1468495870) (extensions tab --> context menu of "..." in the upper right corner --> install from vsix).

Unfortunately, due to a VSCode limitation, you can only reference a problem matcher that is supported by VSCode or any installed extensions via a string name (like "$gcc"). We opened a feature request to the VSCode team to expand the tasks APIs to allow specifying a problem matcher with all the fields, as opposed to a string only.

Makefile Tools and CppTools define the most usual $gcc pattern.
In your .vscode/settings.json, define "problemMatchers" string array for the entries of your "makefile.configurations" array, like in the below example.

    "makefile.configurations": [
        {
            "name": "MyConfiguration",
            "problemMatchers": ["$gcc", "$unknown"],
            "makeArgs": ["V=1"]
        },
    ],

Is there anything different than $gcc that you would need? Until VSCode improves the tasks and problem matcher APIs, the only way you get a new problem matcher is by defining it in the package.json of the Makefile Tools extension and an update on Market Place. We can help with that if you let us know what other regular expressions you need, besides $gcc.

**Comment by hitman-codehq** [comment]
@andreeis many thanks, I tried this as you described and it is working!  The only cross compiler I use is GCC so there is no need for any new regular expressions.

Am I correct in understanding that adding the problemMatchers line to the settings.json is only temporary until a new version of VS Code with your requested improvements is available?

Many thanks for implementing this - it will improve the user experience a lot! 👍
