### ISSUE TITLE
Expose build command to use in tasks

### ISSUE THREAD

**Issue by kmbgit** [microsoft/vscode-makefile-tools#178]
If my makefile (written for gmake) runs a compiler (gcc) then I'd expect the PROBLEMS tab to detect compiler warnings and allow me to click on them to go to the line of code to fix them.  If one makefile does a cd and calls another makefile in another directory then I'd expect VS Code to track that through the Entering/Leaving messages output by gmake so it knows what directory relative paths are relative to.

None of this happens, making this extension a bit useless for software development.

**Comment by bobbrow** [comment]
Thank you for trying out the extension.  This feature request is on our backlog.  You can track it with issue #7.
There is also a way to set this up with `tasks.json` so that you don't need to wait for #7.  We need to write up some documentation/examples for that (it is also recently requested #179).

**Comment by andreeis** [comment]
@kmbgit, besides the problems not detecting warnings, can you describe what other issues you see related to "CD" commands and "entering/leaving"? I suspect there are other problems that happen, otherwise just not having warnings in the problems tab I don't think that would make the extension "a bit useless" :). Do you have a repro project for us?
Can you experiment with this setting "makefile.ignoreDirectoryCommands"? Set it to false.

**Comment by mtnmbr** [comment]
> Thank you for trying out the extension. This feature request is on our backlog. You can track it with issue #7.
> There is also a way to set this up with `tasks.json` so that you don't need to wait for #7. We need to write up some documentation/examples for that (it is also recently requested #179).

Hi,
could you please provide a link to the workarround using task.json? I am not able to get this done with a setup like this:

~~~
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "echoCommand": true,
    "tasks": [
        {
            "label": "Build makfileproject",
            "type": "shell",
            "command": "${command:makefile.launchTargetPath}",
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "problemMatcher": "$gcc"
        }
    ]
}
~~~

**Comment by andreeis** [comment]
@mtnmbr, the launchTargetPath command will resolve to the name of a binary that is built by your project and which you selected as a launch target. This command is used when debugging or launching in the terminal.
You need to generate a make command. Currently, the Makefile Tools extension does not expose a command to reveal how make is invoked according to all the current settings. Let me retitle this GitHub report to track this. Once this is fixed, you would be able to write
"command": "${command:makefile.tasksBuildCommand}" (for example)
Until this is fixed, just write whatever make command you need:
"command": "make all" (for example)
If you are satisfied with how the extension builds your project for how you've configured it, copy paste the "make" command from the output channel. When you run the build command, the output channel will start with listing the command being deduced. When we implement the new "tasksBuildCommand", we will grab automatically that one.

Let us know if using "make all" or some other "make" command line works for you.

**Comment by kmbgit** [comment]
Maybe this isn't a "makefile" problem at all, but one to do with the problem tracker.  In any reasonably-sized system with a compilation phase that converts source code into some sort of executable, you're going to have source files in different directories with each directory having its own "build" process that creates the executable module (think of a C or C++ project where each directory produces a library or an executable).  When you build the entire system, the compilation process visits each directory in turn to build that module before finally combining all the modules into whatever it is that's used to distribute the product (RPM file, Windows MSI, etc).

The trick the problem tracker is failing to do it recognize when the compilation system has changed to a different directory, so any relative path names in error messages are being taken as relative to the start directory for the overall build process, not the individual module subdirectory.  GNU Emacs compilation-mode copes with this by processing the Entering/Leaving messages output by GNU Make.

Of course, Emacs compilation-mode is superior to VS Code in that is doesn't have this daft split of error message recognizers.  If you have a mixed-language project then some errors will come from the C compiler, some from maybe Javac, some from Perl, etc.  The problem tracker should be a lot more eclectic than it is.

Or maybe I should stick with Emacs? :-)

**Comment by andreeis** [comment]
@kmbgit, when we will implement problem matchers support yes we will make sure to calculate the paths properly, even for projects that are CDing all around.

Besides not having that available now, the extension should still provide IntelliSense for your code base and build/debug/launch features which also correctly compute paths and look at "entering directory"/"leaving directory". 

Did you try the tasks.json workaround described above? Except that for "command", you write "make" or "make all" or whatever command you use for building your project. I wonder how your paths will work in that scenario.

**Comment by andreeis** [comment]
@kmbgit, @mtnmbr, we are wrapping up the 0.3 release which contains support for problem matchers without the need of a workaround on your part (unless you need something different than "$gcc").

If you would like, you can install the vsix from [this link](https://github.com/microsoft/vscode-makefile-tools/actions/runs/1463984957). 
- go to the Extensions panel on the left
- click "..."
- run "Install from vsix" from the context menu

I am particulary interested @kmbgit in how this works with your project which I understand from you that has a complex structure with directories being changed during the build.
To implement this new support, we used the tasks and problem matcher framework that VSCode exposes to extension developers. There was nothing specific to paths that we could do. I am curious if this works automatically in your case.
If you find problems with the paths, we can implement for the next release some special handling where we interpret the logs ourselves and create manually every item in the problems tab.
Hopefully, the recommended strategy built in VSCode already can handle your project. I am very curious to find out.

Are you using $gcc problem matcher or you need something else? I am asking because currently, the VSCode framework for this allows new problem matchers to be implemented in the extension. This means a PR and an update release of Makefile Tools. We opened a feature request for their APIs so that in future you could define any new custom problem matcher you need in your .vscode/tasks.json which we would read and pass it further to these APIs.

**Comment by andreeis** [comment]
I forgot to mention that you need to set "problemMatchers" like in the below example in order to make warnings/errors show up in the Problems tab.

Also, let us know if you need any other problem matcher than $gcc. 

    "makefile.configurations": [
        {
            "name": "MyConfiguration",
            "problemMatchers": ["$gcc"],
            "makeArgs": ["any", "other", "args", "you", "want"]
        },
    ],

Until VSCode improves the tasks and problem matcher APIs, the only way you get a new problem matcher is by defining it in the package.json of the Makefile Tools extension and an update on Market Place. We can help with that if you let us know what other regular expressions you need, besides $gcc.

**Comment by andreeis** [comment]
@kmbgit, @mtnmbr, we released Makefile Tools 0.3.0 today which includes problem matcher support. Let us know if you encounter any other issues.

If you would like, you can also leave us a review on [Market Place](https://marketplace.visualstudio.com/items?itemName=ms-vscode.makefile-tools&ssr=false#review-details).

**Comment by andreeis** [comment]
@kmbgit, I am tagging you just to let you know that if your project uses -C or -f pointing to a folder other than workspace folder, the current problem matcher will have trouble finding the source files. Clicking on them won't work for you.
With the soon upcoming 0.4.0, we will fix part of this problem.
With workitem https://github.com/microsoft/vscode-makefile-tools/issues/257 we will address also more complicated scenarios (like possibly yours) where "make" just jumps and builds all around. That will come later though, not sure when.

**Comment by gcampbell-msft** [comment]
Based on reading all of the comments, it seems like we have implemented the features requested from this issue, and any other requests are already tracked elsewhere. With that in mind, I'm closing the issue. 

@kmbgit Please feel free to open a new issue if there are any problems or feature requests that you have! Thanks.
