### ISSUE TITLE
Cant't handle relative include path?

### ISSUE THREAD

**Issue by AlexYzhov** [microsoft/vscode-makefile-tools#183]
Hi everyone, I found out that makefile-tools may not support relative include path passed by "-I" param. The rules in my makefiles are to let compiler search directories relative to the path of source code files. However makefile-tools seems always manage these include paths as absolute or started from "makefile.makeDirectory".

Here are my logs:
[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/6643610/dryrun.log)
[c_cpp_debug_output.log](https://github.com/microsoft/vscode-makefile-tools/files/6643611/c_cpp_debug_output.log)

Will this feature be fixed or added in the future? Or should I change the way I wrote makefiles? Thanks for helps

**Comment by andreeis** [comment]
@AlexYzhov, the extension is calculating, while reading command by command from the dryrun.log, which is the current directory in that particular point. It follows any cd, pushd/popd or -C and once a compilation command is seen, for each of -I switches it constructs a full path from the currently calculated current path and the relative path in the -I. I can't think of a scenario where this wouldn't work so this can't be a feature we'll provide later but a bug fix. Maybe we parse the relative path or the current path wrong.

Pick one example of header that is not properly found, give us the name of that so that we focus only on that in the logs. Also, for that header, how do you reference it in your .c or .cpp files? Give us the exact #include command as you wrote it.

I also need you to set "makefile.loggingLevel" to "Debug" and "makefile.extensionLog" to ".vscode/extension.log" in your .vscode/settings.json, reload and reconfigure your program and share with us .vscode/extension.log.

**Comment by AlexYzhov** [comment]
After your sharing, maybe I got the idea why relative path on my project can't work correctly
My makefile won't do any cd or -C process during making the target, I use relative path to target file instead. 
for example: 
`gcc target.c -o ../relative/path/from/source/files/target.o -I ../relative/path/to/include/files`

The way I wrote makefile may mislead the plugin to do parsing jobs. Adding support on solving path related to target files may solve the problem. 

But these are all my suspicions, I'll capture detailed logs this weekend for more information

**Comment by andreeis** [comment]
Then the extension should parse "../relative/path/to/include/files" and apply it to the root folder where the makefile is. If it doesn't do this it's a bug, we'll see in .vscode/extension.log. If it does this and you don't agree let's discuss what should happen here.
Ok, we'll wait for the .vscode/extension.log. Also if you come up with a whole end to end project that manifests this I can have a look on my side and find more things to help your scenario with less investigation on your side.

**Comment by gcampbell-msft** [comment]
@AlexYzhov Due to the age of this ticket and the length of time that it hasn't had activity, we plan to close it soon if we don't hear anything from you. 

Has this issue been solved for you? We'd love to hear more about it if not, thanks!
