### ISSUE TITLE
.DEFAULT target not supported

### ISSUE THREAD

**Issue by ohenrich** [microsoft/vscode-makefile-tools#184]
The .DEFAULT target doesn't seem to be supported. The recipe specified under .DEFAULT is used for any target for which no rules are found.

**Comment by andreeis** [comment]
@ohenrich, thank you for suggesting this idea that we overlooked. Please clarify (since we didn't use these much), as I read in [Special MAKEFILE Targets](https://www.gnu.org/software/make/manual/html_node/Special-Targets.html), it would be useful if the extension would automatically add to the build targets list the following? ".PHONY", ".SUFFIXES", ".DEFAULT", ".PRECIOUS", ...etc...?

In the mean time, if I understood right this request and you just need to append ".DEFAULT" in your "make" invocatino, you can work around this limitation by adding a new makefile configuration in your .vscode/settings.json:

    "makefile.configurations": [
        {
            "name": "DefaultTargets",
            "makeArgs": [".DEFAULT"]
        },
        {
            "name": "Regular",
            "makeArgs": []
        }
    ],

I am thinking that you need the regular configuration too for when you don't want ".DEFAULT" being appended.
Once we implement this support, you don't need "makefile.configurations" at all.

Please confirm whether I understood correctly the request and if the workaround helps.

**Comment by ohenrich** [comment]
@andreeis Yes, I can confirm what you say is what I was suggesting. These build targets .DEFAULT, etc, ... are not supported at the moment, requiring significant changes to certain Makefiles.

Thanks for suggesting this work around. I will give this a try within the next few days and let you know how it works.

**Comment by ohenrich** [comment]
@andreeis What you suggested doesn't work. The Makefile Tools get stuck in a configuration step. I reverted to my previous fix (replacing .DEFAULT with something else) until you implemented this properly.

**Comment by andreeis** [comment]
@ohenrich, I forgot to mention that after you add those entries in "makefile.configurations", you also need to select the first one "DefaultTargets" either via the command "makefile.setBuildConfiguration" in the palette or via the "..." near the "Configuration" element in the "Makefile Tools" left side UI panel (above of where you select, in the same way, the build target).

If you already did this and the extension is stuck during the configure phase, we still need to figure out why because even when we will implement the support for these new targets, the extension would probably freeze the same way. All the workaround does is generate the same command line that will be generated when this feature will be implemented: which is adding the ".DEFAULT" after the "make" invocation.

After you change the ".DEFAULT" to something else, what is the good working command generated by the extension? You can see it if you read through the "Makefile Tools" output channel. Search for "with command".

**Comment by gcampbell-msft** [comment]
@ohenrich Is this still is an issue for you? 

We are going through issues that haven't had activity for a long time, and we'd love to know if this is still an issue for you so that it can get properly addressed. Thanks!

**Comment by ohenrich** [comment]
> @ohenrich Is this still is an issue for you?
> 
> We are going through issues that haven't had activity for a long time, and we'd love to know if this is still an issue for you so that it can get properly addressed. Thanks!

I'm sorry, but I have no idea in which context I used the Makefiles. But I believe that my comment is related to the fact that when issuing `make` on the command line without any argument this should trigger some sort of default behaviour. But the default target is not specified.

**Comment by gcampbell-msft** [comment]
@ohenrich Understood! We will keep this on the backlog and investigate .DEFAULT targets / default behavior as soon as we have availability. Thanks for following up.

**Comment by andreeis** [comment]
@ohenrich , the behavior of "make" when not given any targets is the same in Makefile Tools extension in VSCode versus in a terminal. But indeed the extension doesn't go out of its way to calculate, what will be the default target that will "win" in that circumstance. It was not a goal for us that when the user does not specify a target we would show the winner. We invoke make with the arguments the user wants (plus we add a few of our own depending what workflow we're running) and then it's on "make". 
Then about the ".DEFAULT", if the user wants to pass it to the command line, we need an entry in "makefile.configurations" setting. If somehow "make" treats ".DEFAULT" in some way that is documented and known (I have to brush up on my understanding of this keyword), "make" will treat it the same when we invoke "make" ourselves. 
So unless I miss something, I don't see anything we can do in this work item without further info from you and I propose we close. Of course we will be prompt in addressing any situation you report if that happens for you again.

**Comment by ohenrich** [comment]
@andreeis Yes, please feel free to close this as I cannot provide more information at the moment. But thanks for getting back to me!

**Comment by ohenrich** [comment]
Closing

**Comment by ohenrich** [comment]
@andreeis Yes, please feel free to close this as I cannot provide more information at the moment. But thanks for getting back to me!
