### ISSUE TITLE
Specifying "--no-print-directory" breaks Browse Path

### ISSUE THREAD

**Issue by btgould** [microsoft/vscode-makefile-tools#197]
When making a recursive make call with `--no-print-directory`, the generated browse path "skips" the intermediate path from the workspace root to the sub directory the next makefile resides in. 
My `settings.json` file currently looks like:
```
{
    "makefile.extensionOutputFolder": "./.vscode",
    "makefile.loggingLevel": "Debug",
    "makefile.extensionLog": ".vscode/extension.log",
    "C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools"
}
```
After a full configure, the browse path listed in `extension.log` has many entries, which all have a similar form to: `path-to-workspace-root-path/path-from-subdir-to-browse-dir`. This causes makefile-tools to generate configurations for files that do not exist, and breaks intellisense for files in my project. 

The actual recursive make call looks like `@${MAKE} --no-print-directory -C path-from-root-to-subdir -f Makefile config=$(prj_config)`. It is the `path-from-root-to-subdir` that is missing from my browse path. After removing the `-no-print-directory` and reconfiguring, the browse path is correctly generated as `path-to-workspace-root-path/path-from-root-to-subdir/path-from-subdir-to-browse-dir`, and intellisense works as expected.
I would just remove the `--no-print-directory` from my makefiles, because the extra printed output doesn't really bother me, but the problem is that all of my makefiles are auto-generated by premake5. I would really like to avoid having to manually edit something that is already automatically generated every time I add a file just to get intellisense to work.

I realize that recursive make calls may not technically be supported (according to the troubleshooting file in this repo), but I also don't want to rewrite my entire build system. Fixing this behavior would be a huge convenience boost (at least for my uses) for this extension.

Environment: Ubuntu 20.04 using version 0.2.2 of the extension

**Comment by andreeis** [comment]
@btgould, if your project happens to also print out commands like "cd", "pushd" that would match the "-C" output when "print-directory" is on, you can try to set "makefile.ignoreDirectoryCommands": "false" and see how the paths are computed then. If the dry-run log is not writing any change directory commands then this setting won't do anything and it's better to remove it from your .vscode/settings.json to keep it cleaner.

Another workaround that I can think of is to create manually a full clean build log with "no-print-directory" off, then point the extension to it via "makefile.buildLog" setting. IntelliSense will be computed from the information parsed in this log. The next time when your makefiles are regenerated, having "no-print-directory" won't affect the extension anymore. Only make sure to regenerate the build log (manually) when you think the makefiles changed source files, compiler flags, ... etc ... anything relevant that would change IntelliSense.

It would be nice to have a switch to disable "no-print-directory" but I wasn't able to find any. I even don't know if having "print-directory" last would undo the effects of "no-print-directory". The extension puts "print-directory" last in the dry-run make command, but as I see from your recursive call example "no-print-directory" is appended later, by make itself.

I'll think of what other tricks we can do in order to get the directories printed without you needing to change anything in your project and the automation.

**Comment by btgould** [comment]
> @btgould, if your project happens to also print out commands like "cd", "pushd" that would match the "-C" output when "print-directory" is on, you can try to set "makefile.ignoreDirectoryCommands": "false" and see how the paths are computed then. If the dry-run log is not writing any change directory commands then this setting won't do anything and it's better to remove it from your .vscode/settings.json to keep it cleaner.

Unfortunately, there are no similar `pushd` or `cd` commands in the generated makefiles. In dryrun.log, there is one `make: Entering directory 'project-root'` at the beginning of the file, and one `make: Leaving directory 'project-root'` at the end, but no other indications that make knows it should be changing directories. Interestingly, in the extension.log file, there are several lines of the form `POPD command or end of MAKE -C: leaving directory project-root and entering directory project-root`. These are placed in the "Parsing for launch targets" section of the log, but I could not find them anywhere else. Just in case, I did try it with "makefile.ignoreDirectoryCommands": "false", and had the same problems. 

> Another workaround that I can think of is to create manually a full clean build log with "no-print-directory" off, then point the extension to it via "makefile.buildLog" setting. IntelliSense will be computed from the information parsed in this log.

Unfortunately, I don't think this would help very much. The vast majority of the times I am regenerating my makefiles, it is because I have added a new source file, which would then require me to manually edit the makefiles again to get intellisense for this new file. 

> It would be nice to have a switch to disable "no-print-directory" but I wasn't able to find any. I even don't know if having "print-directory" last would undo the effects of "no-print-directory". The extension puts "print-directory" last in the dry-run make command, but as I see from your recursive call example "no-print-directory" is appended later, by make itself.

As you said, `print-directory` is passed as an argument in the dry run, but that did not appear to affect anything. I suspect that specifying it at the actual location of the recursive `make` call as premake does it overrides the command line option.

**Comment by andreeis** [comment]
I understand. Then I don't think there is anything that the extension can do in your case. I think we will close this report in a day. If you have any ideas of what can be done for this scenario let us know.
