### ISSUE TITLE
Please make relationship between makefile.launchConfigurations and makefile.configurations clearer

### ISSUE THREAD

**Issue by TryerGit** [microsoft/vscode-makefile-tools#212]
At present, there seems to be no way (at least to someone who is testing out this extension for the first time) to pair a debug launch configuration with a debug build and a release launch configuration with a release build. Prior to coming across this extension, I used to be able to specify in `launch.json` the specific preLaunchTask that was needed to be completed before the particular launch.

So, I had a tasks.json like so:

           "label": "dbgbuild", // make will execute a build with debug appropriate compiler flags
            "type": "shell",
            "command": "make",
            "args": [
                "CONF=Debug",
                "-C",
                "./.vscode"
            ],

            "label": "releasebuild", // make will execute a build with release appropriate compiler flags
            "type": "shell",
            "command": "make",
            "args": [
                "CONF=Release",
                "-C",
                "./.vscode"
            ],

Then, I could refer to these tasks by their `label`s in the appropriate launch in `launch.json` like so:

            "name": "DbgLaunch", // Debug launch
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/.vscode/dist/Debug/GNU-Linux/linux",
            "args": [],
            "preLaunchTask": "dbgbuild" // note the ability to specify the appropriate task

            "name": "ReleaseLaunch", // Release launch
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/.vscode/dist/Release/GNU-Linux/linux",
            "args": [],
            "preLaunchTask": "releasebuild" // note the ability to specify the appropriate task

Currently, in this extension, how can I do this pairing so that depending on the launch I select, the appropriate build /executable is launched?

In `settings.json`, I presently have the following as suggested by the documentation, but it is unclear to me how I can specify different launches, one for release and one for debug:

    "makefile.configurations": [
        {
            "name": "dbgbuild-extension",
            "makeArgs": ["CONF=Debug"]
        },
        {
            "name": "releasebuild-extension",
            "makeArgs": ["CONF=Release"]
        }
    ],
    "makefile.makeDirectory": "./.vscode",
    "makefile.launchConfigurations": [
           //What should go here  and how can this be made to correspond to the makefile.configurations above?
    ]

I would imagine that there should be the ability to specify different launch configurations, each with its own path to the executable as the debug executable will be built in a different folder as compared to the release executable.

Thank you.

**Comment by andreeis** [comment]
@TryerGit, thank you for the idea. Once we implement [this feature](https://github.com/microsoft/vscode-makefile-tools/issues/25), you may achieve this by using variables that would be expanded to debug or release.
Also, maybe we can define the relationship in a more direct way... We will think, so I am keeping this issue opened.

In the meantime, let me explain how launchConfigurations work now.
The extension tries to find as many possibly launch targets by parsing the dryrun log or the build log if you give one via "makefile.buildLog". It looks at the output of all link commands to identify which binaries are of interest and it also looks if it happens that those binaries are invoked with various parameters and constructs a launch target for each of the scenarios identified. A launch target is formed by a CWD path, a binary name and a list of parameters.

Click on the Makefile Tools left side panel, click on the tree node for launch configurations, a quick pick will open with all the possibilities that are detected and select one. It's possible none are detected, maybe the build does not log the link steps in a verbose way. Once you select one launch target from the quick pick, the extension writes a launchConfigurations entry in settings.json automatically.

You can also write manually any entries for launchConfigurations, or modify an existing one. The extension will fill that quick pick with all the scenarios that it identifies from parsing the dryrun or build log plus anything different that is found in the array.

Indeed, currently there is no connection between a launch configuration and a makefile configuration. But still, if you are interested in building before debugging, the extension will invoke make with all the current parameters (that you set already) when you want to debug the current launch configuration. It's true that without a clear correspondence, you may build something different than what is selected as launch configuration. So we will think how to best fix this scenario.

**Comment by TomIowaSoft** [comment]
This is exactly the information that needs to be included on the documentation web pages.  The documentation web pages only covers simple working case with no details on how it works or what to do when it does not work, which is often.

**Comment by TomIowaSoft** [comment]
Only specifying the binary is of little use when the binary is .elf.  There does not appear to be any way to specify use of DBG in a launch target either.  If I launch dbg from a launch.json configuration, then Intellisense does not know the correct paths to include files.  Is there a way to make this work?

**Comment by andreeis** [comment]
I am surprised that when you use launch.json you don't have IntelliSense. Something else is wrong, let's find out. Did you configure before you "F5"? A project is configured when it is loaded (unless you set "makefile.configureOnOpen" to "false") or when you manually run from the palette either of the commands "Makefile: Configure" or "Makefile: Clean Configure".

Please set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log" in .vscode/settings.json, load your project, let it configure (or run the command yourself), open the files that don't have IntelliSense working and share with us the following files from the .vscode subfolder: extension.log and dryrun.log. I hope to spot quickly what is wrong and help you get IntelliSense back when you use launch.json.

Regarding the other debugging route (launchConfigurations), you can specify a debugger via "makefile.defaultLaunchConfiguration.MIMode" (which can be gdb or lldb) and "makefile.defaultLaunchConfiguration.miDebuggerPath" which is useful when the gdb/lldb you want is not on the path.
Setting these two within "defaultLaunchConfiguration" is global to all launch configurations and can also be overwritten inside any items of the launch configurations array.

Let us know if any of this helps.

**Comment by TomIowaSoft** [comment]
I do have intellisense, but there are some header files that exist in multiple locations in the path and it goes to the wrong one. Which one it should use depends on the makefile target built.

I made an adjustment to the build location and now it shows a build path when I click on the Launch Target: [Unset] pencil, but selecting it does not change [Unset].  

Clicking on the debug icon builds it again and then it shows 
"Cannot debug because there is no launch configuration set. Choose one from the quick pick."

So I select the path shown in the launch target quick pick and it says:
"Running the contributed command: 'makefile.outline.launchDebug' failed".
 Launch target remains
[settings_json.txt](https://github.com/microsoft/vscode-makefile-tools/files/7488847/settings_json.txt)
 [Unset] 

	"makefile.launchConfigurations": [
		{
			"cwd": "${workspaceFolder}/mcu/_build_mcu1",
			"miMode": "gdb",
			"miDebuggerPath" : "C:/Tools/GNU Tools ARM Embedded/7 2017-q4-major/bin/arm-none-eabi-gdb.exe",
		}
	],

In the extension.log I see this for one of the files using the wrong path. 
Configuration for file d:\OneDrop\sano-potentiostats-firmware\wpstat\arduino\hardware\sano_samd\variants\sano_wpstat_mcu2_5\variant.cpp was not found. CppTools will set a default configuration.

The correct path is:
D:\OneDrop\sano-potentiostats-firmware\wpstat\arduino\hardware\sano_sam\variants\sano_wpstat_mcu1

I recently inherited this project from someone that did all their editing in a text editor.  I am still working on understanding what they were doing in the makefile. I will adjust the makefile as needed once I understand what vscode is looking for.

[dryrun.log](https://github.com/microsoft/vscode-makefile-tools/files/7488808/dryrun.log)
[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/7488809/extension.log)

**Comment by TomIowaSoft** [comment]
vscode just updated to 1.62.0 and everything is the same, except now I get a new popup message when I select the launch target.  _The "path" argument must be of type string. Received undefined_

**Comment by andreeis** [comment]
@TomIowaSoft, several issues here.
I suspect that the MCU2 file is opened because a problem in the CppTools extension. I will follow up with the team and confirm.

Regarding launch configurations, I noticed that there is no binaryPath and binaryArgs defined in the one launchConfigurations entry. From what I see in the logs, I think you want "binaryPath" set to d:\OneDrop\sano-potentiostats-firmware\wpstat\mcu\_build_mcu1\mcu1.elf. And probably empty args array. Maybe that is because setting the launch target failed with that error you mentioned (which I'll investigate).

Try first to reset the state of your project. Delete "launchConfigurations" from your .vscode/settings.json. Run the command "Makefile: Reset state for troubleshooting" from the palette. Then go again in the "C++" left panel, select again "MCU-1" configuration, let the project get reconfigured (which should happen automatically if you don't have "makefile.configureAfterCommand" set to "false") and try to select the launch target again. Let me know how this goes.

If setting the launch target still has an issue, you just edit your launch configuration entry manually.

**Comment by TomIowaSoft** [comment]
Yes, it now lets me select a launch configuration.  Thank you.
However, I can't test it at the moment until I have it compiling again after recent code changes.

**Comment by TomIowaSoft** [comment]
Since the makefile launch target was not working I use using a configuration in launchJson.  How does the makefile launch configuration know about these launch parameters?

**Comment by andreeis** [comment]
This extension was designed to help when using launch.json as well, as an alternative (most often for more complicated scenarios) to using the debug target command (which only does create a temporary simple launch.json on the fly to pass to the debugger).

To avoid hard coding things in "cwd" or "program", you can use these commands that the extension will answer automatically:

${command:makefile.launchTargetDirectory}, ${command:makefile.launchTargetPath}, ${command:makefile.launchTargetFileName}... and a few others plus variations.
You can read more about this [here](https://github.com/microsoft/vscode-makefile-tools/blob/main/docs/makefile-settings.md).

**Comment by andreeis** [comment]
@TomIowaSoft , do you still reproduce any of the issues we discussed here besides the original proposal of launchConfiguration versus makefile configuration relationship? I would like to close the ticket if all others are addressed by now with the latest release 0.7.

Regarding the possibility of having launch target change automatically after a change of configuration or after a change of build target (item https://github.com/microsoft/vscode-makefile-tools/issues/254). Is item 254 what you had in mind or an additional scenario?
