### ISSUE TITLE
Using the extension as configuration provider does not work

### ISSUE THREAD

**Issue by TryerGit** [microsoft/vscode-makefile-tools#214]
Hello,

I would really like this extension to succeed because currently I have to go through many hacks to get what I want including playing around with `launch.json` and `tasks.json` amongst others. I am encountering many issues with this extension as of now. In due course, I will make separate posts on these so that developers here can understand the issues that a user may face.

My current issue is that if I choose this extension (makefile tools) as the configuration provider, I get red squiggly lines indicating that something is amiss. 

See imgur link : https://imgur.com/rxOiGCH

I attach my entire project which includes the following folder/file structure:

---include\
        maininclude.h
---src\
        Main.cpp
---.vscode\
        Various make related files
[New folder.zip](https://github.com/microsoft/vscode-makefile-tools/files/7250993/New.folder.zip)

Please let me know if anything is needed for reproducing at your end.

**Comment by andreeis** [comment]
@TryerGit, thank you for the project, that will be very helpful. We will have a look at it in the beginning of next week, since we are preparing a new release of another project.
Everything is squiggling, indicating that nothing works with IntelliSense or only some instances of things?
If you set "makefile.loggingLevel" to "Debug" and "makefile.extensionLog" to "extension.log" in your .vscode/settings.json, share with us the files .vscode/extension.log and .vscode/dryrun.log". Maybe I can quickly spot something obvious. Of course, next week I will clone the project and see everything myself.

**Comment by gcampbell-msft** [comment]
@TryerGit I've downloaded your project and it seems that these issues have been fixed! I was able to open the project and see great Intellisense and navigate throughout the project easily. Could you confirm that your issues are fixed? 

Unless I hear from you that there are still issues, this issue will be closed upon our next official release. Thanks!
