### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dragonmux** [microsoft/vscode-makefile-tools#215]
[ms-vscode.makefile-tools-unresponsive.cpuprofile.txt](https://github.com/microsoft/vscode-makefile-tools/files/7255857/ms-vscode.makefile-tools-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `makefile-tools`
- Extension Version: `0.2.2`
- OS Version: `Linux x64 5.14.8-arch1-1`
- VS Code version: `1.60.2`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by andreeis** [comment]
@DX-MON, can you set "makefile.loggingLevel" to "Debug" and "makefile.extensionLog" to "extension.log" in your .vscode/settings.json and share with us the files .vscode/extension.log and .vscode/dryrun.log? It's very common for such situations to have a project for which the command "make --dry-run --always-make" calls scripts like configure infinitely.

You can get unblocked by producing manually a full clean build log of your project and pointing the extension to it via "makefile.buildLog". This will skip over the make --dry-run invocation and should parse anything that is needed from there. You would only need to recreate the build log when relevant build changes are made (related to source code files, compilation switches... anything that impacts IntelliSense).

**Comment by DX-MON** [comment]
We'll switch those flags for the Makefile plugin in a little bit and see what that does.

As for the other part, this is happening when we start VSCode - the project is already configured (via the command line) + built and we're doing nothing special to cause this other than simply opening VSCode - this is what the plugin is choosing to do as its first steps on this project (before we even get to a usable InteliSense environment)

Rachel.

**Comment by andreeis** [comment]
@DX-MON, even if your project is already configured and built in the command line, the extension still needs to read some "make" output and parse useful things that enable the features to work. That is why the first thing the extension does after a project is loaded in VSCode is run "make --dry-run" and a few other switches to produce this output.

--dry-run would normally not execute anything in your project, it just lists commands, but --always-make (which we need, otherwise the output is too small and contains nothing that we need to parse) may trigger some unusual targets to be run (configure and such).

See this document for more details about some known and challenging scenarios: [troubleshooting](https://github.com/microsoft/vscode-makefile-tools/blob/main/docs/troubleshooting.md).

When you tweak the settings (loggingLevel and extensionLog) and prepare the files for us (dryrun.log and extension.log), don't set also "buildLog". The "buildLog" setting is a workaround for you to get unblocked that I recommend you do after you share the files. This skips over the --dry-run --always-make invocation of make. 

Also if you share your project with us we can have a look at it from all angles and advise you how to best set it up. And fix any bugs we find while testing with your repository.

**Comment by vredzhepov** [comment]
Is it possible to disable makefile extension for the specified makefile project?

**Comment by andreeis** [comment]
@vredzhepov, one way to disable the extension (without uninstalling it or disabling it globally) is to make it fail to find the makefile. Set "makefile.makefilePath" to something that does not exist. You will get an annoying popup every time you open your project and you can ignore it. We have a work item for the future where you can press a button in a similar popup to never notify you again.

Also, can you tell us why do you want to disable the extension for the project? Maybe we can help you fix the problem so you benefit of all the features implemented in "Makefile Tools".

**Comment by dragonmux** [comment]
Apologies this got left - we never were able to get you those extra logs and haven't been able to repro it recently, so we're opting to close the issue as "fixed"
