### ISSUE TITLE
`makePath` does not work

### ISSUE THREAD

**Issue by schperplata** [microsoft/vscode-makefile-tools#237]
On my system, `make` command is not defined - make and other compiler tools are not on PATH. 
It seems like `makefile.makePath` is not properly resolved. [Similar to this issue](https://github.com/microsoft/vscode-makefile-tools/issues/236), I've experimentally discovered, that:
* If `makefile.makePath` is defined in X.code-workspace `settings` group, absolute path to the `make.exe` is a valid settings. Leaving only the path to the folder where `make.exe` can be found, is not enough.
* Any setting in .vscode/settings.json didn't work for me. 

How this should work? Can the extension docs be a bit more precise about how user should configure these settings?

**Comment by andreeis** [comment]
@schperplata, regarding relative paths, we will look at handling that scenario more robustly. Hopefully https://github.com/microsoft/vscode-makefile-tools/issues/25 will be enough.

Before I close this as a duplicate, I want to verify if there is anything else not working properly.

You're saying that "any setting in .vscode/settings.json" doesn't work for you? Not even full path?

When you define in X.code-workspace, are you saying that giving full path (folder only, no file name) doesn't work? I think that should. We append make.exe when we detect we're given a path only.

**Comment by schperplata** [comment]
Example, this does not work (*.code-workspace file):
![image](https://user-images.githubusercontent.com/8736111/145726560-ca97f962-3752-4ff8-9840-2e625680483d.png)
So, `make.exe` is not appended automagically.

Specifying `makefile.makePath` in 'settings.json' in any form didn't work either. This is the only valid configuration I was able to make, that is in *.code-workspace file:
![image](https://user-images.githubusercontent.com/8736111/145726794-5698db5e-4203-4ba8-9513-0045f24a9d49.png)
... that is absolute path to .exe file.

**Comment by andreeis** [comment]
@schperplata, I confirm this is broken. It was working at some point in the past. The reason is that the extension thinks that "bin" is the tool (because we allow other tool names besides "make"), appends the extension to it and it will try to build with "bin.exe". We will fix this (if the path seen is a folder, we append make if the path points to a file we don't append).
Thank you for describing this scenario.

**Comment by andreeis** [comment]
@schperplata, we released Makefile Tools 0.4.0 today which contains the fix for this issue and also worth noting, localization support. If you happen to use VSCode language packs, give Makefile Tools a try in your preferred language.
Let us know if you encounter any issues: with the translated strings, any other bugs or if you have any feedback for the future of this extension.
