### ISSUE TITLE
Multple config project. Switching makefile to parse and build project with different defines and sources

### ISSUE THREAD

**Issue by nfhktwrbq** [microsoft/vscode-makefile-tools#260]
In my project is multiple configs. Each configuration has its own makefile.
Are there any options to select (config) makefile for parsing and building within the same vscode window? 
I'm think that new window for each config (makefile) is inconvenient.

**Comment by andreeis** [comment]
@nfhktwrbq, yes.
If you want to have IntelliSense for all at once and to even build all of them with one single command, write a makefile wrapper that would invoke a MAKE for all the projects.
Main, wrapper MAKEFILE:
all:
	$(MAKE) -C ./first/folder
	$(MAKE) -C ./second/folder
...

But if every project needs some additional and unique environment, args, etc..., you can switch from one to another without leaving your VSCode instance, but you would build and access IntelliSense only for one at a time. You still need a new root makefile but in this case it doesn't need to wrap the others, it can even be empty (it's to ensure the extension activates). Or you can run a "makefile" command, anything (like "configure") from the pallette to ensure the extension activates in case you don't have one makefile in the root.

In the root of .vscode\settings.json, define one "makefile.configuration[]" entry for each makefile:
    "makefile.configurations": [
      {
          "name": "FirstConfig",
          "problemMatchers": ["$msvc"],
          "makeDirectory": "./first/folder",
          "makeArgs": [
              "arg1", "arg2"
          ]
      },
      {
          "name": "SecondConfig",
          "problemMatchers": ["$gcc"],
          "makeDirectory": "./second/folder",
          "makeArgs": [
              "arg3", "arg4"
          ]
      },

We are looking forward to hear more about your scenario. Let us know if any of this helps.

**Comment by asdaqsamir** [comment]
Thank you for this. This helped me configure my build and test projects. See my settings.json below. I have a question and a possible bug to report. 

Request: preConfigureScript does not work separately for the config, it has to be globally defined. For example, look at the TEST section of the following settings.json which works, however it didn't work when I added it to the "Test" named configuration.
```
{
    "makefile.loggingLevel": "Debug",
    "makefile.extensionOutputFolder": ".vscode",
    "makefile.extensionLog": "extension.log",
    "makefile.makePath": "${workspaceFolder}/../../../make/bin/make.exe",
    /////////////////////////////////// TEST //////////////////////////////////
    // "makefile.preConfigureScript": ".vscode/test_preconfig.bat",
    // "makefile.alwaysPreConfigure": true,
    /////////////////////////////////// TEST //////////////////////////////////
    "makefile.configurations": [
        {
            "name": "Build",
            "makeDirectory": "build",
            "makefilePath": "build/makefile_tgt_gcc_4.8.2_x86-64.mk",
            "problemMatchers": [ "$gcc" ],
            "makeArgs": [
                "-j", // optional j prefix requires the number of thread as given below
                "15", // optional number of threads with prefix j
                "-O", // optional syncing of output with parallel threads
                // "keypad_comm.o", // optional single file compilation
            ],
        },
        {
            "name": "Test",
            "makeDirectory": "build/test",
            "makefilePath": "build/test/makefile_test.mk",
            "problemMatchers": [ "$gcc" ],
            "preConfigureScript": ".vscode/test_preconfig.bat", // not supported yet in a separate config so uncomment the TEST above
            "alwaysPreConfigure": true,                         // not supported yet in a separate config so uncomment the TEST above
            "makeArgs": [
                "-j", // optional j prefix requires the number of thread as given below
                "15", // optional number of threads with prefix j
                "-O", // optional syncing of output with parallel threads
                "WIN64_EXE_TGT_ONLY" // uncomment for building test
            ],
        },
    ],
    "C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools",
    "C_Cpp.default.mergeConfigurations": true,
}
```
test_preconfig.bat
```
@REM Create master list only used in Test config
pushd build
./post_bin.bat -sf
popd

@REM Copy the dll to test folder for testing only used in Test config
pushd build\test
.\test_prereqs.bat
popd
```

Possible Bug: When I changed the config name from "Default" to "Build"; VS Code was giving error "Makefile entry not found". So I renamed it back to "Default", changed the config to "Test" from the UI and than renamed the "Default" to "Build" again and it worked.

**Comment by asdaqsamir** [comment]
@andreeis maybe something like this for the above if/else for .json if not in the .bat file:

```
    "if": {
        "makefile.configurations.name": "Test"
    },
    "then": [
        {
            "makefile.preConfigureScript": ".vscode/test_preconfig.bat",
            "makefile.alwaysPreConfigure": true,
        }        
    ],
```

**Comment by andreeis** [comment]
@asdaqsamir, thank you for continuing to use the extension.
We plan to implement the local (configuration level) setting for preconfigure script soon (0.8 release ETA end of June, while 0.7 out next week if all goes well). In the meantime, having it only at global level is indeed limiting. Unfortunately you can't use if/then constructs in the settings json. Brainstorming what else you can do, even if convoluted, to be able to achieve your scenario until we implement the local setting.

We fixed a bunch of issues related to "Makefile entry not found", you can try the private vsix from [here](https://github.com/microsoft/vscode-makefile-tools/actions/runs/4451312188) until we release 0.7 and see if anything improved for you.
Regarding the "Default" string, it is an unfortunate assumption I made in the beginning. Currently, if no configuration is selected, we set a variable to "Default". You need to have a different string than that and it should work, no errors, I'll help you get unblocked if something still happens for you with the new vsix. We will also fix the "Default" string issue.

**Comment by andreeis** [comment]
@asdaqsamir , note that 0.6 is not able to expand ${workspaceFolder}, use full paths for now. 0.7 comes with a set of variables expansion scenarios.

Back to your goal, you can invoke the preconfigure script (temporarily, until the local setting support) from the makefile and not via the extension pre-configure step. Here's one idea of how you can achieve what you need with the current functionality.

In each "makefile.configurations[]" entry, add an extra makeArg into the array, like: "MODE=BUILD" and second "MODE=TEST".
In the entry point makefile, somewhere in the beginning, you can add:
ifeq ($(MODE) , BUILD)
	./.vscode/preconfig_build.bat 
else ifeq ($(OPT) , TEST)
	./.vscode/preconfig_test.bat
else
endif

Let me know if this works for you.

**Comment by andreeis** [comment]
@asdaqsamir, since you mentioned variables expansion before:
While we wrap up the final testing for the 0.7.0 release, if you would like you can preview the variable expansion feature if you download [this vsix](https://github.com/microsoft/vscode-makefile-tools/actions/runs/4703905680) and install it via the "Install from VSIX" command in the palette. 

Besides the highly requested ${workspaceFolder} and ${workspaceRoot} macros that work now from any setting entry-point, we support also:
- ${userHome}
- ${env:ENVIRONMENT_VARIABLE}
- ${config:any_extension_scope.any_setting_id}
- ${command:any_extension_scope.any_command_name} (this one worked already in launch and tasks json but now they work in settings.json as well). Makefile Tools has the same launch commands we implemented for a while already and you can use any other command that is available. If it returns something useful, we'll expand with the return value.
- ${configuration} (variable syntax) and ${command:makefile.getConfiguration} (command syntax, accessible in launch tasks json as well) both return what is the current active configuration (what you selected in the left UI, either one of the entries in makefile.configurations from settings.json or "Default")
- ${buildTarget} and ${command:makefile.getBuildTarget} map to what build target you selected in the UI (or via the command set build target), so it can be "all" or any other individual target from your makefile or expands to empty if you didn't select anything in the quickPick.

If by any chance you need to pass strings with the varexp syntax and you don't want us to expand it use \\ to escape it (maybe you pass ${something} via makeArgs or binaryArgs). If that happens in a path, use forward slash for path separator so that we don't confuse it with the escape character.

If we don't recognize the pattern within ${} or something happens while running the referenced command or... we expand to "unknown".
If the first expansion resolves to another ${} varexp syntax we complain in the log that we don't support yet multiple expansion passes and the result is still "unknown". We will support more complex scenarios in future.

Any feedback?

**Comment by andreeis** [comment]
@asdaqsamir , any of the issues discussed here remained unaddressed or still repro with the latest release? Unless we hear back from you with issues about what was discussed here, we will close soon.
