### ISSUE TITLE
Unexpected notation kept declared: Building the current makefile configuration "run"

### ISSUE THREAD

**Issue by 1475505** [microsoft/vscode-makefile-tools#267]
1.When I make with target (including run,gdb), This notations kept active for infinite time and must choose cancel, else I cant handle the terminal and run my project.
2.When run: After cancel, the program is running and I can handle it.But it`s buggy.
3.When gdb: The terminal will run gdb with gdb`s welcome. But after cancel, the gdb is killed and I can't run gdb and program.
4.A single c file can build and debug normally.
My settings is :(Ubuntu20.04)
```
{
    "makefile.launchConfigurations": [
        {
            "cwd": "/home/ics/build",
            "binaryPath": "/home/ics/build/out",
            "binaryArgs": []
        }
    ],
    "C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools"
}
```
launch.json 
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "g++ build and debug active file",
      "type": "cppdbg",
      "request": "launch",
      "program": "${fileDirname}/${fileBasenameNoExtension}",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${workspaceFolder}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ],
      "preLaunchTask": "g++ build active file",
      "miDebuggerPath": "/usr/bin/gdb"
    }
  ]
}
```
task.json
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "label": "g++ build active file",
      "command": "/usr/bin/g++",
      "args": ["-g", "${file}", "-o", "${fileDirname}/${fileBasenameNoExtension}"],
      "options": {
        "cwd": "/usr/bin"
      },
      "problemMatcher": ["$gcc"],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

**Comment by andreeis** [comment]
@1475505, I am not able to understand exactly all the angles of this problem. Do you have infinite execution time for the "configure" step and/or the "build"step or only debug or launch in terminal?

When you debug, do you run "F5" (which reads from your launch.json) or the "Debug" button present in the Makefile Tools left side panel (which triggers the "Makefile: Debug target" command)?

Can you easily share your project with us? If it's not open source, we also have an internal Microsoft email that other developers from the Makefile Tools community have been using: makefiletools@microsoft.com.

**Comment by 1475505** [comment]
> 

I 
Configure step is normal.The question is:
I have infinite execution time when pressing "debug" icon in Makefile tools(not the F5, because it's a project) . The note "Building ..." will kept shown, while the project is running in the terminal (not the debug console, not gdb) with the note "Building..." . After "cancel", the note exits and the make stopped unsuccessfully - "The miDebugger Path is invalid".

"Run" option: will run project in terminal with note, run again after cancel.

It's all OK when F5 just for a single c file(not a project with Makefile).

**Comment by andreeis** [comment]
@1475505, does setting "makefile.buildBeforeLaunch": "false" in your .vscode/settings.json unblock you? This should let you debug or run in terminal without triggering a build of your project.

Was this happening before 0.3.0, when a build was not running via tasks in terminal but you would see the build output simply in the output channel? Or you weren't using this extension before this release?

What happens when you build your project via our build commands and buttons? Do those build operations finish?

Ultimately, run "debug" or "run" again, let the "Building..." popup appear and then copy paste what is the build command line that the extension calculates? You can see that in the output channel. Is that command succeeding for you in another context? Or do you wish to build with a different command and the extension is not calculating properly what it should be? Do you set a build target in the Makefile Tools left side panel?

**Comment by 1475505** [comment]
Solved. It`s a special project.
