### ISSUE TITLE
Login shell on Linux

### ISSUE THREAD

**Issue by mfrailis** [microsoft/vscode-makefile-tools#273]
While I have no issue in building the code in the default terminal (opened on a docker container in vscode):

<pre>
$ make all
.....
cmake --build build.x86_64-conda_cos6-gcc93-o2g --target all -- 
gmake[1]: Entering directory `/home/user/Work/Projects/EL_ImageLib/build.x86_64-conda_cos6-gcc93-o2g'
gmake[2]: Entering directory `/home/user/Work/Projects/EL_ImageLib/build.x86_64-conda_cos6-gcc93-o2g'
</pre>

using this extension the "make all" fails with 

<pre>
The terminal process "bash '-c', ''make' 'all''" failed to launch (exit code: 2)
</pre>

The reason seems that I need a "login" shell, i.e. I need to force bash to be run with the "-l" option, e.g.

/usr/bin/bash -l -c "make all"

Is  it possible to force the "-l" option in the terminal opened by Makefile tools? The Makefile tools extension is installed in the container.

Thank you for any support.

**Comment by andreeis** [comment]
@mfrailis, I will investigate. Does this happen when you run the "Makefile: Build Target" command or you press the "build" icon in the Makefile Tools left panel UI? When we do this, we use the tasks support built in VSCode. We don't code anything specific to what kind of terminal to use and how to invoke it. Hopefully I will find a solution or workaround for you.

What are your "terminal" settings (check user level and workspace level)?

How is the "Makefile: Configure" working for you, any similar issues, terminal related, in how the extension is spawning the "make" process? Do you have proper IntelliSense in your code base when you use Makefile Tools? I am asking because I see that you are also using cmake. If all that "make" does is spawning cmake, depending how that output looks like, we may not have good text to parse to deduce compilers, arguments, source files, defines, includes, standard, etc...

Just for a sanity check (and our curiosity for projects that combine makefiles and cmake), can you set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log" in your .vscode/settings.json and share with us the files extension.log plus dryrun.log from .vscode subfolder?

And regarding your original request (-l bash) I will get back to you.

**Comment by mfrailis** [comment]
Hi @andreeis, I just solved it. You comment "When we do this, we use the tasks support built in VSCode" was helpful.
My "terminal.integrated.shell.linux" was set to null everywhere (user, workspace, devcontainer.json).

Then I have added the following to the user settings
<pre>
    "terminal.integrated.profiles.linux":  {
        "bash_login": {
          "path": "/usr/bin/bash",
          "args": ["-l"]
        }    
    },
    "terminal.integrated.defaultProfile.linux": "bash_login"    
</pre>

and now the shell is initialized properly by Makefile Tools inside the docker container (sourcing the .bashrc), before running make all. 

It is something we need because the g++ compiler, libraries and python modules are provided through a conda environment, that has to be sourced. 

Some additional information:
- using the above terminal settings in the devcontainer.json ("settings" section) was not helpful
- so I have moved it in the user settings of VSCode (I'm working on Linux)  and this solved the issue

In our project, for building, we use a software extending CMake (https://github.com/degauden/Elements). It forces a given source structure  and it requires a top level Makefile with standard targets, including "configure", "all", "test", "doc", "install", "purge", etc. (https://github.com/degauden/Elements/blob/develop/Makefile)

I'm using the Makefile Tools "build" icon. The "all" target is recognized automatically and that's enough.

Concerning your requests, I have now the Makefile Tools log, but no dryrun.log:

<pre>
$ cat extension.log 
Configurations cached at /home/user/Work/Projects/EL_ImageLib/.vscode/configurationCache.log
No path to the makefile is defined in the settings file.
No folder path to the makefile is defined in the settings file.
Always pre-configure: false
Dry-run switches: --always-make,--keep-going,--print-directory
Additional compiler names: 
Exclude compiler names: 
No current configuration is defined in the workspace state. Assuming 'Default'.
Reading current build target "all" from the workspace state.
No current launch configuration is set in the workspace state.
Default launch configuration: MIMode = undefined,
                    miDebuggerPath = undefined,
                    stopAtEntry = undefined,
                    symbolSearchPath = undefined
Configure on open: true
Configure on edit: true
Configure after command: true
Only .PHONY targets: false
Save before build or configure: true
Build before launch: true
Clear output before build: true
Ignore directory commands: true
compile_commands.json path: null
Deduced command 'make ' for configuration "Default"
Saving opened files before build.
Exception thrown during the configure process: Cannot read property 'ActiveClient' of undefined
Sending telemetry: eventName = configure
properties: firstTime = "false",makeDryRun = "true",readCache = "false",isClean = "true",processTargetsSeparately = "false",resetBuildTarget = "false",triggeredBy = "configure dirty (on open), settings (configureOnOpen)",buildTarget = "all"
measures: numberBuildTargets = "0",numberLaunchTargets = "0",numberIndexedSourceFiles = "0",numberMakefileConfigurations = "0",totalElapsedTime = "0.3",exitCode = "-5"
Configure elapsed time: 0.3
Sending telemetry: eventName = settings
properties: makefile.loggingLevel = "Debug",makefile.makeDirectory = "undefined",makefile.makefilePath = "undefined",makefile.extensionOutputFolder = "undefined",makefile.extensionLog = "..."
No configurations defined in makefile.configurations setting.
Saving opened files before build.
Building target "all" with command: 'make all'
Executing task: "Makefile Tools Build Task" with quoting style "Strong"
 command name: make
 command args all
Target "all" built successfully.
Sending telemetry: eventName = build
properties: exitCode = "0",target = "all",triggeredBy = "command pallette (buildTarget)"
measures: buildTotalElapsedTime = "3.243"
</pre>

Thanks a lot.

**Comment by andreeis** [comment]
@mfrailis, probably dryrun.log is missing because there is some exception happening during configure. I haven't seen that before, not sure what is going on.
`Exception thrown during the configure process: Cannot read property 'ActiveClient' of undefined`
It doesn't look like a standard makefile project and probably the CMake Tools VSCode extension is covering IntelliSense. Probably you can still use Makefile Tools for build, debug and/or launch. We plan to look closer in the future at projects where make and cmake coexist.

**Comment by mfrailis** [comment]
Thanks for checking.
Closing now the issue since it is solved for me.
