### ISSUE TITLE
Disable optimisations if debugging

### ISSUE THREAD

**Issue by Tim1808** [microsoft/vscode-makefile-tools#277]
I don't know if this should be in the scope of this extension, but whenever I am coding c++ I use gcc as my compiler, usually with `-O2` in my makefile as a flag.

However, when I am debugging I would like it to automatically build a version with `-O0` (minimal optimizations), which makes for a better debugging experience. 

Is this workflow possible?

**Comment by andreeis** [comment]
@Tim1808, in general we noticed that makefiles are written with specific scenarios and flags for debugging, release, etc... We didn't think the extension should add automatically a particular switch for debugging, especially since there is more than one possibility (-g, -O0, other switches...) and we preferred to leave this choice to the users.
If this would really make a difference for some user scenario, we could add a new setting, off by default, which would contain details on what compiler switches to be automatically added. We will wait and see the reactions from the community (thumb-ups, comments, etc...) to properly triage when this would be addressed.
We can also review and test a PR if anyone from the community is interested in implementing this before we get to it.

**Comment by TheOddZer0** [comment]
The why many of us rather use make than CMake or Meson (or others) for some projects is because we have the control of everything. Automatically adding compiler flags would defy the purpose of using Make. Let's not also forget that there really are a lot of ways Makefile writes accept extra compiler flags, some don't accept any. Some use things like CFLAGS_EXTRA, MY_CFLAGS or etc (in case of C). So that would also complicate the process of passing the right flags.
One way to get the best of both worlds would be to pass an extra argument on invocation of make (like DEBUG=1) so we (in the Makefile) can handle adding the right flags.

**Comment by andreeis** [comment]
Closing, since the scenario of giving an argument to "make" (like DEBUG=1) and based on it passing different other flags to compiler/linker is supported already. Nothing new to do here. Reactivate if I missed anything.
