### ISSUE TITLE
Beginner friendliness "Settings"

### ISSUE THREAD

**Issue by kevinlinxc** [microsoft/vscode-makefile-tools#292]
The documentation mentions settings like `makefile.configurations` and `makefile.makefilePath`. I am a beginner to vscode, so I don't know how to access these. Could someone inform me, and consider adding a mention in the readme?

**Comment by kevinlinxc** [comment]
Figured it out a bit. I was trying to figure out how to add args to the launch, it seems you open the projects .vscode/settings.json and this is where you can put `makefile.x` settings. A way to discover that directly from the documentation (if I'm not just missing it) would be nice

**Comment by kevinlinxc** [comment]
It seems like when I pass "binaryArgs" to makefile.launchConfigurations, they only get passed for "Run in terminal", and not "Debug" - how do I pass args when debugging?

**Comment by andreeis** [comment]
@kevinlinxc, regarding binaryArgs, we should see them whether you debug your application or run it in the VSCode terminal. Let's find what the bug is. Please set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log" in your .vscode/settings.json, open your project again in VSCode, let it configure, then send us the files dryrun.log and extension.log from the .vscode subfolder.

**Comment by andreeis** [comment]
@kevinlinxc , this ticket is old and we were not sent the requested info for repro. Let us know if this still happens. We will close soon.

**Comment by kevinlinxc** [comment]
Apologies, I don't even remember what project this was for.
