### ISSUE TITLE
Regression: extension is disabling itself incorrectly

### ISSUE THREAD

**Issue by willco007** [microsoft/vscode-makefile-tools#304]
Starting with version 0.3.0, the makefile tools extension is disabling itself when loaded.  My guess is that it's not finding my makefile so it's disabling itself (?). 

The value for the path to my make file is:

"makefile.makefilePath": "${workspaceFolder}/generated/MakeFile"

The file does exist and reverting to 0.2.2 re-enables the extension as expected.

I'm on Fedora 35.

VSCode:
Version: 1.66.0
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:41.156Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.16.18-200.fc35.x86_64 snap

**Comment by andreeis** [comment]
@willco007, how about the 0.4 release? We did several bug fixes in the area of enabling/disabling the extension features based on finding or not the makefile.

Also, note that we don't have yet support for variable expansion, so using ${workspaceFolder} in your Makefile Tools settings doesn't work. Use plain paths.

**Comment by andreeis** [comment]
@willco007, I don't have an estimate regarding when we will have variable expansion support (limited resources to work on this project) but it will be among the first new features that we will implement in the near future.

Share with us your makefilePath setting as it looks now, without using the variable.
Also, if you manually run the "Makefile: Configure" command from the palette, does Makefile Tools enable again?

**Comment by andreeis** [comment]
Ok, I forgot, it would help if you also set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log", reload the project in VSCode, then run manually the "Makefile: Configure" command, let configure finish... then share with us .vscode/extension.log and .vscode/dryrun.log files.

**Comment by willco007** [comment]
Here you go:

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiPgu--hI_3AhXUFDQIHWikCJYQFnoECAcQAQ&url=https%3A%2F%2Fpremake.github.io%2Fdocs%2Fpropertydefinition%2F&usg=AOvVaw1cnsfewUQ9ACWmg691WYIx

**Comment by andreeis** [comment]
@willco007, all looks good in the log. Where do you "open folder" for your project or run "code ." in terminal from? Or, to ask differently the same thing, where is your .vscode/settings.json?

Regardless of your setting "makefile.makefilePath" (which appears in your log that we process correctly), if you open from a location that doesn't have any makefile under somewhere, Makefile Tools won't know to activate to even begin reading what's in makefilePath. But when you run the "Configure" command, we activate, read makefilePath and all else will automatically start to work.
We are considering for future to always activate and deactivate after some analysis, but now we activate on detecting a makefile anywhere inside the path that is opened in VSCode, then we deactivate after analysis.

I looked at all the paths in your log. I would open from PlayDate and have my settings.json (with the makefilePath) in .vscode there. If you need to open from a location outside PlatDate/Simulator (I saw core, source, etc...) you can also create a small empty makefile anywhere it doesn't bother you withing the folder structure that you load in VSCode. This will activate the extension and because we will read makefilePath we will find all the pieces fine. It's a hack to work around the fact that we don't activate if we don't detect a makefile anywhere within the folders that get loaded in VSCode.

**Comment by willco007** [comment]
My structure, and where I run VS Code from, is this:

<Playdate>
-><SimulatorWX>  <- Folder is VS Code root
->->.vscode/settings.json
->->generated/Makefile
...

Pretty bog standard. The Makefile is below the root as you can see.

I don't want to use Playdate as root because: 1) it's huge and disables git 2) it contains a bunch of stuff I don't need/want

**Comment by andreeis** [comment]
@willco007, makes sense. I don't know then why the extension doesn't activate or doesn't stay enabled if you open from SimulatorWX while having a makefile inside (and yet it stays active if you run the configure command immediately after load). Also from the log you shared, I didn't see any of the messages that complain about us not finding the makefile, I hoped to find more clues there. If you happen to have the project open source I would try it from my side.

**Comment by willco007** [comment]
Not open source unfortunately. That's why they call them bugs I guess. 🙂

**Comment by willco007** [comment]
So one interesting thing I just noticed was when I run the "Makefile: Configure" command the status line in the VSCode status bar says "Activating Extensions". Shouldn't they already be activated automatically when I open VS Code? Is that, perhaps, why this extension isn't loading correctly?

**Comment by andreeis** [comment]
@willco007, I wasn't able to find a bug similar to this in the VSCode GitHub repository but I have another suspicion from our code base. I will implement some temporary logging and build a vsix that you can temporarily install and produce a log with more hints for us. Especially since you say this worked fine in 0.2.2.

**Comment by willco007** [comment]
I just noticed, another project I have that also uses make files loaded the extension just fine when I opened the project. I have this feeling it's the size of my project (which is very large) that is causing the extension not to load initially. Is that a possibility?

**Comment by andreeis** [comment]
@bobbrow, could this be similar to the reason we needed to change the CMake Tools activation from anywhere within the opened folder to just 3 levels?

**Comment by andreeis** [comment]
@willco007 , does this still happen? Just checking on old stale tickets.

**Comment by willco007** [comment]
@andreeis Nope, it appears fixed. I've been using it for the last several months and I had completely forgotten about this bug as it's working as expected. Thanks for following up, I'll close this issue.
