### ISSUE TITLE
Cencel button on "Generating dry run" pop-up doesn't work

### ISSUE THREAD

**Issue by olimexsmart** [microsoft/vscode-makefile-tools#317]
Clicking on "Cancel" in the pop-up that shows when opening a Makefile project causes a flooding of terminal window being opened and closed in rapid succession. It entertained my colleagues :joy:, I wasn't able to use the PC since all the other windows kept loosing focus.

The duration of this phenomenon is roughly the same to leaving the process complete, so the Cancel button seems to not have any effect in stopping the underlying process.

This bug was present from previous releases too.

**Comment by andreeis** [comment]
@olimexsmart, very interesting indeed :) but I am sorry that you are experiencing this. The cancel button works in general, on the projects we tested on. If your project is open source or you can come up with a repro for us, let us know.
Otherwise, set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log", open the project again in VSCode, cancel, wait until the end of the process (just in case, so we don't miss a possible clue) and share with us .vscode/extension.log and .vscode/dryrun.log.

Also, to work around this, what happens if you let one such long configure finish and then later reload? We cache the result and while a new configure will still be long in the background (one that would make sure everything is up to date) you would have almost instantaneously the results of the previously cached configure. Is this scenario working for you?

Additionally, you can significantly shorten the configure time by not invoking "make' at all. Set "makefile.buildLog" to a file that represents the log of a full clean build that you invoke in terminal and redirect its output. Configure will be almost instantaneous as well, you will have all the features, but indeed that will become out of date when you modify compiler flags, add/remove source files... anything that impacts IntelliSense and which results from you changing the build of your project. So you would have to know when to regenerate this full clean build log. The other features work the same, with "make --dry-run" used for configure or with a pre-created build log.

**Comment by olimexsmart** [comment]
I generally let the dry-run complete, without that I would miss lot of syntax highlighting. So in general this is not much of an issue. 

I'm attaching the log file generated while hitting the button and the problem showed up. 

If you remember me from #156 you will know that I work on close-source, weird-ass embedded compilers. I don't expect to fall in the general use cases for this extension. 

> Also, to work around this, what happens if you let one such long configure finish and then later reload? We cache the result and while a new configure will still be long in the background (one that would make sure everything is up to date) you would have almost instantaneously the results of the previously cached configure. Is this scenario working for you?

This doesn't work for me. Like mentioned in #156, I have to delete the .vscode/*.log before opening VSCode file to have IntelliSense working (syntax highlighting and completion suggestion are my main uses cases. Errors have to many false positives so I disabled them). 

If you can suggest a setting that doesn't use caching at reload, maybe that would be the best solution for me.

 
[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/8629561/extension.log)

**Comment by andreeis** [comment]
@olimexsmart, indeed something weird is going on for your case. I didn't see anything useful in the log but it was funny to see "Configure succeeded" among the various non succeeding return codes.
I can build a temporary vsix with lots of logging that you can install when you have time with the hope that I may see something. In a few days.

Otherwise, to avoid such long configure time, point the extension to the full clean build log of your project (that you create manually in terminal outside VSCode) via "makefile.buildLog". It should give you all you need, except that you need to refresh it when you add/remove source files or when you add/remove/change relevant compilation switches or compiler names.

**Comment by andreeis** [comment]
@olimexsmart , do you still see this? I apologize for not getting back to you sooner with a vsix and the extra logging. Let us know if this is still an issue or we can close.

**Comment by olimexsmart** [comment]
Hi, meanwhile I contributed to the Great Resignation and changed work, life and also the technology stack 

From what I remember, in the last months of the job (ended in December 2022) the dev environment was ok in general. 

Thanks for the follow up and have a great day
