### ISSUE TITLE
Can I skip configure? It is too slow.

### ISSUE THREAD

**Issue by audetto** [microsoft/vscode-makefile-tools#319]
Hi,

I have a project at work with about 140 sub projects for a total of about 11000 cpp files to be compiled.

I have tried to use this extensions and I am not sure how to handle the configuration step.
It takes more than 5 minutes with no obvious results, and it runs more often than not.

Can I skip it altogether?
What I was hoping to do is:

1. select makefile
2. select target
3. specify extra arguments
4. build

What does the configure step gives me for such a long wait?

There are some stats at the end:

- generateParseContent: 19
- parseIntelliSense: 371
- parseLaunch: 8

configure elapsed time: 437

**Comment by andreeis** [comment]
@audetto, if your project happens to be open source let us know and we can have a look to see if we can spot any workflow improvements for you or bugs in the extension.

If not, please set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log", reload your project, let it finish configure and share with us the files .vscode/dryrun.log and .vscode/extension.log.

If you let the configure finish once, the second time you load the project the features should work because we load the previous configure results from a cache. Is that not working for you?

Regarding a first time configure of 5 mins, often it is expected for large projects. To be sure there is nothing else wrong going on, we should see the logs or get a repro.

A much quicker configure (almost instantaneous) would be to not let the extension invoke "make --dry-run" when configuring, but point it to a full clean build log that you would generate separately from a terminal. Set "makefile.buildLog" to the output of such a full clean build of your project. We parse all we need from there. Otherwise, we invoke "make --dry-run" and parse the output of that but sometimes there are issues for large projects or conflicts between "--dry-run" and "--always-make", not bugs in the extension but various weird behaviors of make, depending how the makefiles involved are written (like sometimes --dry-run and --always-make result in infinite execution of various targets).

In the left side UI panel of this extension, you can select a target ("Build target") and a configuration other than "Default", like "FirstConfig" or "SecondConfig" if you define in .vscode/settings.json something like:

"makefile.configurations": [
{
    "name": "FirstConfig",
    "makeArgs": [
        "arg1", "arg2"
    ]
},
{
"name": "SecondConfig",
    "makeArgs": [
        "arg3", "arg4"
    ]
},

**Comment by audetto** [comment]
The project is not open source. I will see what the log contains and see if I am allowed to take them out, but I doubt.

One think I do not understand, and maybe adding a few lines in the doc would really help, is what is the purpose of `configure`.

Are you trying to figure out the command line for each `.cpp`? Which files are compiled? What are the valid targets?
The output will contain a lot of custom improvements to pretty print to the console, how can you parse it?

I want to see what happens is I detect the configure step and produce a dummy output. Or if you tell me what you are looking for, I can try to produce just this as fast as possible.

**Comment by andreeis** [comment]
@audetto, thank you for the suggestion to improve the documentation. We can explain there in more detail that the "configure" process is what gives the extension the information needed to parse what are the compilers and flags used for each source file, the current folder (used to compute correct full paths from relative paths), what are targets that the makefile can build and what are the binaries (also targets in the makefile) that look like tests or executables that the developer wants to execute from time to time. All of this to be able to provide in the UI easy access for the user. And most of all to be able to offer correct IntelliSense during coding. Without "configure", only features like building or debugging/running (with additional settings done by the user) may work.

About using "makefile.buildLog", I am not sure we can parse everything. With every scenario that we encounter via our customers we improve the parsers. You need "make" to produce output that is verbose enough. I've seen many repositories with very cryptic (and useless for us) output. Sometimes V=1 helps, if you pass it to make. Or makefile directives that prevent silencing of the output. But if your complaint is only that configure is slow, not that it is incorrect, then it means that the output of "make --dry-run --keep-going --always-make --print-directory" (which is the command run by "configure") is verbose enough for us to parse. Run that command once in the terminal, outside VSCode, save the output then feed it to the extension via "makefile.buildLog".

It's true that the left UI is not available until the "configure" process is completed, but that should happen only when we don't find a cache from a previous configure. You are saying that even if you allowed configure to run before until the end, the second time the UI is disabled until configure finishes for a second time? That would be a bug.

Also, if you want to access the UI without being blocked by the configure, you can also set "makefile.configureOnOpen" to false in settings.json. Of course, you lose the configure step and all that brings with it. I don't think you need to do that. Let's see why configure doesn't work for you properly the second time. I know you said it's too long, but once you can afford to let it finish, overnight or something. Then I want to make sure the non clean configure (which reads from cache and unblocks everything and offers you all the features) works.

**Comment by andreeis** [comment]
@audetto, found this while looking through active tickets. Know that now the left UI is available even if the configure process did not start or failed or is running. But only the "Configuration" quick-pick. The build/launch targets edit controls are accessible but would popup a message that their data is not up to date until configure finishes. They would still populate with older info.

Otherwise, is configure still slow for you? We have a fix in the works from the community for an infinite loop during the configure process but I believe that is not what you are seeing, correct? Your configure does finish, but after a long time.

Since most likely this is by design, we are interested in closing this ticket. Let us know any of the workarounds I proposed work for you.

**Comment by ronoaldo** [comment]
I believe this is the same issue I started to face recently. Looks like the loadFromCache operation is the one to blame here:

```
No current configuration is defined in the workspace state. Assuming 'Default'.
No target defined in the workspace state. Assuming 'Default'.
Dropping various extension output files at /home/ronoaldo/.config/Code/User/workspaceStorage/f20aee7c969ee0b6aea3347e4ab749a9/ms-vscode.makefile-tools
Logging level: Normal
Configurations cached at /home/ronoaldo/.config/Code/User/workspaceStorage/f20aee7c969ee0b6aea3347e4ab749a9/ms-vscode.makefile-tools/configurationCache.log
No path to the makefile is defined in the settings file.
No folder path to the makefile is defined in the settings file.
Always pre-configure: false
Dry-run switches: '--always-make', '--keep-going', '--print-directory'
No current launch configuration is set in the workspace state.
Default launch configuration: MIMode = undefined,
                    miDebuggerPath = undefined,
                    stopAtEntry = undefined,
                    symbolSearchPath = undefined
Configure on open: true
Configure on edit: true
Configure after command: true
Only .PHONY targets: false
Save before build or configure: true
Build before launch: true
Clear output before build: true
Ignore directory commands: true
compile_commands.json path: null
Deduced command 'make ' for configuration "Default"
Saving opened files before build.
Configuring from cache: /home/ronoaldo/.config/Code/User/workspaceStorage/f20aee7c969ee0b6aea3347e4ab749a9/ms-vscode.makefile-tools/configurationCache.log
Load configuration from cache elapsed time: 52.443
Generating in the background a new configuration cache with command: 'make --dry-run --always-make --keep-going --print-directory'
Writing the dry-run output: /home/ronoaldo/.config/Code/User/workspaceStorage/f20aee7c969ee0b6aea3347e4ab749a9/ms-vscode.makefile-tools/dryrun.log
Generating dry-run elapsed time: 0.009
Preprocessing: "/home/ronoaldo/.config/Code/User/workspaceStorage/f20aee7c969ee0b6aea3347e4ab749a9/ms-vscode.makefile-tools/dryrun.log"
Preprocess elapsed time: 0
Parsing for IntelliSense.
Updating the CppTools IntelliSense Configuration Provider.
Parsing dry-run output for CppTools Custom Configuration Provider.
Parsing for IntelliSense elapsed time: 0.002
Parsing for launch targets.
No launch configurations have been detected.
Complete list of launch targets: 
Parsing for launch targets elapsed time: 0.002
Generating parse content for build targets.
Generating targets information with command: 'make all --print-data-base --no-builtin-variables --no-builtin-rules --question'
Writing the dry-run output: /home/ronoaldo/.config/Code/User/workspaceStorage/f20aee7c969ee0b6aea3347e4ab749a9/ms-vscode.makefile-tools/targets.log
Generating dry-run elapsed time: 0.011
Parsing for build targets from: "/home/ronoaldo/.config/Code/User/workspaceStorage/f20aee7c969ee0b6aea3347e4ab749a9/ms-vscode.makefile-tools/targets.log"
Found the following 3 build targets defined in the makefile: all;bundle;clean
Complete list of build targets: all;bundle;clean
Parsing build targets elapsed time: 0.001
Configure finished. The status for all the subphases that ran:
loadFromCache: return code = 0, elapsed time = 52.443
generateParseContent: return code = 0, elapsed time = 0.009
preprocessParseContent: return code = 0, elapsed time = 0
parseIntelliSense: return code = 0, elapsed time = 0.002
parseLaunch: return code = 0, elapsed time = 0.002
dryrunTargets: return code = 1, elapsed time = 0.011
parseTargets: return code = 0, elapsed time = 0.001
Configure succeeded.
Configure elapsed time: 52.487
```

**Comment by ronoaldo** [comment]
I think I see what is going on... I have some Makefiles which are not to build c/c++ code, and the extension seems to be always running the default target to build some kind of caching.

**Comment by andreeis** [comment]
Considering I did not hear from @audetto I would close this ticket for the problem that is described in the first part of the ticket.
@ronoaldo, I am thinking now at the problem that you describe. I never saw the phase of "load from cache" take this long. Is your project open source or are you able to send us a zip (makefile-external@microsoft.com) or can you create a smaller repro?
Regarding makefiles that don't build c/c++, that's irrelevant. "make --dry-run" will generate a dryrun.log that does not contain c/c++ compiler nor linker commands, we don't parse anything useful for CppTools, we should finish quickly in that situation and the cache generated would be empty (no 0 bytes, but just a small file containing the structure we use, zero entries, etc...). Something else happens here.

**Comment by ronoaldo** [comment]
@andreeis - I am observing two different behaviors. Sometimes (usually the first time I open VS code in a given day) it takes around ~50s to configure it. Other times, it takes around 7-8s. If I manually run `make --dry-run` it is very quick.

I have a repository where it can be used to take around 8s on my machine: github.com/ronoaldo/mercurio. I tested today and for two-three times it took that many seconds to configure. I tested renaming the workspace folder mentioned in the output log (the one inside ~/.config/Code) but I could not trigger the 50s delay again after the first one.

I have several other extensions too, is there a way to share them? I am looking for the issue here as it is the one that produces the log and the one that seems to "block" Code startup once I open a workspace, but it could be elsewhere.

I appreciate the help.

**Comment by ronoaldo** [comment]
Today I opened the shared [public repo](https://github.com/ronoaldo/mercurio) and for the first time it took 52s:

```
No current configuration is defined in the workspace state. Assuming 'Default'.
No target defined in the workspace state. Assuming 'Default'.
Dropping various extension output files at /home/ronoaldo/.config/Code/User/workspaceStorage/e0d496c6b1969b928f8a461b8e80db8c/ms-vscode.makefile-tools
Logging level: Normal
Configurations cached at /home/ronoaldo/.config/Code/User/workspaceStorage/e0d496c6b1969b928f8a461b8e80db8c/ms-vscode.makefile-tools/configurationCache.log
No path to the makefile is defined in the settings file.
No folder path to the makefile is defined in the settings file.
Always pre-configure: false
Dry-run switches: '--always-make', '--keep-going', '--print-directory'
No current launch configuration is set in the workspace state.
Default launch configuration: MIMode = undefined,
                    miDebuggerPath = undefined,
                    stopAtEntry = undefined,
                    symbolSearchPath = undefined
Configure on open: true
Configure on edit: true
Configure after command: true
Only .PHONY targets: false
Save before build or configure: true
Build before launch: true
Clear output before build: true
Ignore directory commands: true
compile_commands.json path: null
Deduced command 'make ' for configuration "Default"
Saving opened files before build.
Configuring from cache: /home/ronoaldo/.config/Code/User/workspaceStorage/e0d496c6b1969b928f8a461b8e80db8c/ms-vscode.makefile-tools/configurationCache.log
Load configuration from cache elapsed time: 53.133
Generating in the background a new configuration cache with command: 'make --dry-run --always-make --keep-going --print-directory'
Writing the dry-run output: /home/ronoaldo/.config/Code/User/workspaceStorage/e0d496c6b1969b928f8a461b8e80db8c/ms-vscode.makefile-tools/dryrun.log
Generating dry-run elapsed time: 0.13
Preprocessing: "/home/ronoaldo/.config/Code/User/workspaceStorage/e0d496c6b1969b928f8a461b8e80db8c/ms-vscode.makefile-tools/dryrun.log"
Preprocess elapsed time: 0
Parsing for IntelliSense.
Updating the CppTools IntelliSense Configuration Provider.
Parsing dry-run output for CppTools Custom Configuration Provider.
Parsing for IntelliSense elapsed time: 0.026
Parsing for launch targets.
No launch configurations have been detected.
Complete list of launch targets: 
Parsing for launch targets elapsed time: 0.075
Generating parse content for build targets.
Generating targets information with command: 'make all --print-data-base --no-builtin-variables --no-builtin-rules --question'
Writing the dry-run output: /home/ronoaldo/.config/Code/User/workspaceStorage/e0d496c6b1969b928f8a461b8e80db8c/ms-vscode.makefile-tools/targets.log
Generating dry-run elapsed time: 0.142
Parsing for build targets from: "/home/ronoaldo/.config/Code/User/workspaceStorage/e0d496c6b1969b928f8a461b8e80db8c/ms-vscode.makefile-tools/targets.log"
Found the following 15 build targets defined in the makefile: all;backup;build;fix-perms;restore;rm-submodule;run;run-client;shell;stop;submodules;test;update;updated-mods;volumes
Complete list of build targets: all;backup;build;fix-perms;restore;rm-submodule;run;run-client;shell;stop;submodules;test;update;updated-mods;volumes
Parsing build targets elapsed time: 0.187
Configure finished. The status for all the subphases that ran:
loadFromCache: return code = 0, elapsed time = 53.133
generateParseContent: return code = 0, elapsed time = 0.13
preprocessParseContent: return code = 0, elapsed time = 0
parseIntelliSense: return code = 0, elapsed time = 0.026
parseLaunch: return code = 0, elapsed time = 0.075
dryrunTargets: return code = 1, elapsed time = 0.142
parseTargets: return code = 0, elapsed time = 0.187
Configure succeeded.
Configure elapsed time: 54.252
```

The project shows this for 50s and then it finishes loading the VS Code plugins:

![image](https://github.com/microsoft/vscode-makefile-tools/assets/564649/3a28c5ff-d0ba-425c-90cd-ccca78245d64)

These are the folder contents mentioned in the log:

[ms-vscode.makefile-tools.tar.gz](https://github.com/microsoft/vscode-makefile-tools/files/13218665/ms-vscode.makefile-tools.tar.gz)
