### ISSUE TITLE
Not c/c++ projects will also run, resulting in the production of some unnecessary files.

### ISSUE THREAD

**Issue by wenbingzhang** [microsoft/vscode-makefile-tools#325]
Not c/c++ projects will also run, resulting in the production of some unnecessary files.

**Comment by wenbingzhang** [comment]
```
 "makefile.configureOnOpen": false,
```
I set "configureOnOpen" to "false" by default.
"configureOnOpen" cannot be configured by language.

**Comment by andreeis** [comment]
@wenbingzhang, I am glad that you got unblocked by using the setting "makefile.configureOnOpen". I assume that is why you closed this issue. I just want to add the explanation that the Makefile Tools extension activates when it finds a makefile at the root of the folder you open or anywhere downlevel from there. It is by design. In future we will add more complex analysis to this behavior (like deactivate Makefile Tools when CMake Tools is active). Feel free to suggest us anything you'd like to see around the activation of the extension.
Is your project using CMake?

**Comment by wenbingzhang** [comment]
> @wenbingzhang, I am glad that you got unblocked by using the setting "makefile.configureOnOpen". I assume that is why you closed this issue. I just want to add the explanation that the Makefile Tools extension activates when it finds a makefile at the root of the folder you open or anywhere downlevel from there. It is by design. In future we will add more complex analysis to this behavior (like deactivate Makefile Tools when CMake Tools is active). Feel free to suggest us anything you'd like to see around the activation of the extension. Is your project using CMake?

I also use makefile in golang, and I would like to not turn on the "makefile tool" plugin in golang.
