### ISSUE TITLE
Doesn't work with a makefile that calls other makefiles 

### ISSUE THREAD

**Issue by SeanPcWoo** [microsoft/vscode-makefile-tools#326]
My project is a "BSP project", it will build different boards bsp elf. The project Makefile format like this:
![image](https://user-images.githubusercontent.com/20737902/169195190-4030cbf1-35ea-447e-a734-c287d346ef79.png)

the 'Makefile Tool' extension‘s log:
![image](https://user-images.githubusercontent.com/20737902/169195332-15e6028c-182c-4cc5-877b-f69cbd9110e7.png)

I can not create the compiledb file. Is there any methods to solve this problem.

**Comment by andreeis** [comment]
@SeanPcWoo, although makefiles calling other makefiles can be tricky and we definitely don't handle all scenarios yet, we still cover some basic ones. In your case, even dryrun.log looks pretty cryptic and there is not much we can do. We rely on a dryrun that logs which folders goes into and what projects it builds. What happens if you build with V=1? More info shows up maybe? Or are you aware of other flags or makefile directives that will convince "make" to be more descriptive?

Besides this, just by looking at the pictures you shared, if you can't find a way to produce a more verbose dryrun.log, then you could define as many configurations as boards you have, like this, in your .vscode/settings.json and then select one (unfortunately, only one at a time, not all at once) via the left side UI panel ("C/C++" icon), "Configuration" UI element. You will be able to have accurate IntelliSense, build/debug/run targets only of the one board project that is selected at the current time.

"makefile.configurations": [
    {
        "name": "ConfigBoard1",
        "makeArgs": ["-j", "16"],           <---------- either add "all" here as a makeArg or select it from the left side UI panel
                                                                           there is a "Build target" below "Configuration"
        "makeDirectory": "folder/for/board1"    <------- this will generate a -C argument to be passed to "make"
    },
    {
        "name": "ConfigBoard2",
        "makeArgs": ["-j", "16"],
        "makeDirectory": "folder/for/board2"    
    },
   ... ... ...
]

**Comment by andreeis** [comment]
@SeanPcWoo , we are about to close. Let us know if you are still blocked. Try the above workarounds. Or try to make your build output more verbose.
