### ISSUE TITLE
how to launch a target with project configurations ?

### ISSUE THREAD

**Issue by Sarah-Callies** [microsoft/vscode-makefile-tools#344]
My projects need a configuation file, how to start the target ? 
By using lauch.json and set the configuration file in the args?

**Comment by andreeis** [comment]
@Sarah-Callies, for some more complex scenarios (like embedded development for example) you need a launch.json but for most cases the "debug" and "launch" buttons in the Makefile Tools UI panel (left area in VSCode) should be enough, eventually with some extra settings in .vscode/settings.json.

Load your project in VSCode, let it finish configuring, then go to the left UI panel for Makefile Tools and chose a lunch target. If you find the extension is not identifying what executable binaries you build in your project (the quick pick in the upper area of VSCode is empty or doesn't have the values you expect) then let's figure out whether it's a bug in the extension or a limitation in how your project is set up (like maybe you're using silencing directives that cause "make" to not produce the output we need to parse in order to automatically detect stuff for you).

So, if you are not seeing any binaries to chose from in the launch target quick pick, set "makefile.loggingLevel": "Debug" and "makefile.extensionLog": ".vscode/extension.log" in your .vscode/settings.json , reload your project, let it configure and share with us files "dryrun.log" and "extension.log" from the ".vscode" subfolder.

Or if your project is open source, you can point us to it and we'll do this part of the investigation as well.

**Comment by Sarah-Callies** [comment]
1. I can "Build target" and see the executable binaries to "Launch target" ;
2. My project is a http server based on c++, the executable binaries  need a configure file to tell it some parameters like server port exc. I do not know how to tell the Makefile tools where the configure file is , and I set the args in the launch.json;
3. When I Launch the bebug button in the Makefile tools, it showed me: Unable to start debugging, Programe path '/usr/local/hub2/server_frame/sum_trans_hub is missing or invalid, GDB failed with the message: "/usr/local/hub2/server_frame/sum_trans_hub" not in executable format: FIle format not recognized;
4. I can launch the executable binaries by script
5. so what is the way to solve this problem?

**Comment by andreeis** [comment]
@Sarah-Callies, share with us your launch.json which you say it works and I can help you set the equivalent in .vscode/settings.json so that you debug the Makefile Tools extension route.

**Comment by andreeis** [comment]
@Sarah-Callies , closing as old but please reactivate if we can still assist with anything.
