### ISSUE TITLE
makefile tools not activating

### ISSUE THREAD

**Issue by oiLAB-project** [microsoft/vscode-makefile-tools#351]
I am using the VSCode in OSX. The makefile tools does not get activated, and I don't see the build/run button on the left vertical panel. The Makefile is in the @workspacefolder. When I press the reload button in the extension, the whole project gets loaded but the reload button is still on. Also makefile setting do not exist in the workspace settings. So I am inferring that the tool is not getting activated. Thanks.

**Comment by andreeis** [comment]
@oiLAB-project, that's strange. We've never encountered a situation where the extension would not activate while having a Makefile in the root folder. How do you open your code base? Do you "Open Folder" from the path which contains the Makefile?

On the left vertical panel, you don't see a build/run button but how about the other UI elements in the Makefile Tools panel? Maybe you send us a screenshot of what you see.

What happens when you manually run the command "Makefile: Configure" from the command palette? Any change in UI being available and the extension activated? That's one way to force activation on Makefile Tools.

**Comment by andreeis** [comment]
Closing old "more info needed" ticket. Please reactivate if this still happens and provide the requested info so that we can reproduce and investigate.
