### ISSUE TITLE
How to use Makefile Tools with ssh remote?

### ISSUE THREAD

**Issue by ReichertL** [microsoft/vscode-makefile-tools#360]
Hi,
I program and test my code in Visual Studio Code on a remote server to which I connect via ssh. 
The code is compiled with a make file.
Although the Makefile Tools are installed and enabled (on the Server), I can not use the tool or access it via the GUI. 
Am I missing something or is support for this feature simply not implemented yet?
Thank you for your  help.
Best,
Leonie

**Comment by bobbrow** [comment]
In general, remote workspaces shouldn't look any different from local workspaces when you have the VS Code Remote extensions installed.  The feature should "just work," so if it's not working, something may not be configured properly.  Can you set the `makefile.loggingLevel` setting to `Debug` (on the remote workspace) and rerun your scenario?  Then share the log with us and we will see if anything stands out.

**Comment by ReichertL** [comment]
Hi,
Thanks for your reply. 
From the logs I got the info that makefile.makefilePath was blank. 
When reconnecting to the Remote Server I also got the message: "Makefile entry point not found".
Setting makefilePath to '${workspaceFolder}/Makefile' also gave me the same error message, but absolute paths seem to be ok. Wildcards seem to be broken.

My Makefile(s) are hidden in serveral Folders. What would be the correct setting so the extensions finds all of them? 
Here is also the log. 
[log_vscode_makefile-tools.txt](https://github.com/microsoft/vscode-makefile-tools/files/9581758/log_vscode_makefile-tools.txt)

**Comment by ReichertL** [comment]
I will try a Wrapper Makefile then.
Thanks a lot for the fast replies and the great help, @andreeis  and @bobbrow!

**Comment by andreeis** [comment]
@ReichertL, I am closing this ticket since it appears we answered all the questions but please reactivate if I overlooked something.
Also in the meantime, variable expansion support was implemented with 0.7.0 in April, I hope you already had a chance to try it. Multi root not yet but we are thinking of another quick workaround to offer more flexibility to the original workaround described in issue 90 until multi root is implemented fully. Stay tuned.
