### ISSUE TITLE
Add option to only configure the extension when explicitly asked

### ISSUE THREAD

**Issue by fcharron** [microsoft/vscode-makefile-tools#367]
I develop some projects that use Makefiles, others CMake, Go, and plenty of different build systems. I would like the option to only get notified or problems (particularly via popups) when I **manually** try and configure Makefile-based projects. 

Currently, even if I disable "Configure On Open", "Configure On Edit" and "Configure After Command", I still get a notification when a "Makefile entrypoint [is] not found", which is rather annoying.

I always want to get Makefile syntax highlighting, but rarely need Makefile automatic build configuration.

**Comment by andreeis** [comment]
@fcharron, thank you for your feedback. We can address your first suggestion (a less annoying user scenario regarding notification popups) for the next release. Makefile syntax highlighting is on our future roadmap, not currently supported.

**Comment by andreeis** [comment]
@fcharron  , we removed the popup notifications regarding makefile and make missing, we left the logging about that unchanged and we are also showing now the "C/C++" tab UI on the left side even when before it was hidden. In there we add now some extra elements about status on make/makefile/build.log: path where we search for them, if not found, you can click the edit pen icon to open settings and change this state via settings like "makefile.makefilePath", "makefile.makePath", "makefile.buildLog" and their "makefile.configurations[]" counterparts.

This will be released with 0.7 next week but if you would like to see how this works earlier you can install one vsix from [this link](https://github.com/microsoft/vscode-makefile-tools/actions/runs/4451312188).

go to the Extensions panel on the left
click "..."
run "Install from vsix" from the context menu

Let us know if you encounter any other issues or if you have any other suggestions/recommendations in this area of functionality.

Otherwise, I am closing this report since the request of configuring only when explicitly asked is achieved via "makefile.configureOnOpen": "false", the popups are gone and the makefile syntax highlighting is tracked with a family of work items targeting makefile language service features that we will address in future.
