### ISSUE TITLE
Extension doesn't work if make is installed on WSL

### ISSUE THREAD

**Issue by Butanium** [microsoft/vscode-makefile-tools#369]
As `make` is installed on my Ubuntu WSL, I can't add it to my PATH but I can use it through the command line. However the extension fails with "Make not found"
<img width="329" alt="image" src="https://user-images.githubusercontent.com/55806347/195099054-01b8e1a6-f832-45a4-83bb-faf7552c2c4f.png">

Project structure : 
```
.
├── main
├── main.s
├── makefile
├── note.md
├── test
└── test.s
```

**Comment by bobbrow** [comment]
Are you running the extension on Windows and trying to reach into WSL?  Or are you opening the WSL folder using the `Remote - WSL` extension in VS Code?  If you are trying to run a linux program in the Windows context, I don't think it will work.  If the problem is just that the extension can't locate your copy of `make` when you open the WSL folder, then you can use the `makefile.makePath` setting to tell us where it is.

**Comment by andreeis** [comment]
@Butanium , is this still a problem? We will close this issue soon because it is stale. Unless we hear back.

**Comment by Butanium** [comment]
Sorry I didn't reply to the previous question :/. I don't use WSL anymore so I won't be able to reproduce the issue, let's just close this then

**Comment by Drixitel** [comment]
I'm using WSL and trying to use the extension C/C++ Makefile Project, and this is still an issue. It does not work on WSL.

**Comment by Butanium** [comment]
@Drixitel see @bobbrow comment above, it should help to troubleshoot your issue

**Comment by gcampbell-msft** [comment]
@Drixitel Following up as well. 

Could you provide us more information about what's not working and _how_ it's not working? What is your use case, what is your setup like, and what project are you using?

Any information you can provide would be great in order for us to investigate this. Thanks.
