### ISSUE TITLE
dry run improperly running recipes in make

### ISSUE THREAD

**Issue by ashblair** [microsoft/vscode-makefile-tools#396]
The dry run is improperly running recipes to remake dependency files.
(the GNU-make program doesn't do this.)
Here's an example from the targets.log file:
      bin/dbg/src/PolyExceptions.cpp.d: src/PolyExceptions.cpp src/PolyExceptions.cpp inc/first.hpp inc/PolyExceptions.hpp
      #  Implicit rule search has been done.
      #  Implicit/static pattern stem: 'PolyExceptions.cpp'
      **#  Last modified 2022-12-09 17:33:42.632510556**
      #  File has been updated.
      #  Successfully updated.
      #  recipe to execute (from 'Makefile', line 163):
	      @$(CXX) $(CXX_FLAGS) -I$(INC) -MM $< -MF $@
	      @STEM=$(subst .cpp,,$*) ; \
	      sed -i "s,$${STEM}.o,$(BLD)/$(SRC)/$${STEM}.cpp.o $@," $@ ;
	      @echo new depend file compiled [$@] >> $(DEPFILE)

The Last modified time above is incorrect.
Here's the directory listing with the full-time option:
-rw-rw-r-- 1 ash ash  4994 **2022-12-05 17:56:47.771570138** -0500 PolyExceptions.cpp

I believe the time in the targets log is when the "dry run" program touched the files, not when they were actually modified.

If you would like to see this problem for yourself, please clone ashblair/Polynomial, run make, close VSCode and then open it again.

**Comment by andreeis** [comment]
@ashblair, please confirm, does the "dry-run" step (that the extension invokes when loading your workspace) break the expected incremental build scenario of your project? Like, when you build not clean, do any of the source files get re-compiled or libraries re-linked even if they are not out of date?
If you set "makefile.loggingLevel": "Debug", you can inspect the output channel and see the "make" commands we use for the "dry-run" phase and for the "targets" phase (different phases with different goals). Let us know if you have suggestions of different "make" switches we can use to achieve the same goals.
The goal for the "dry-run" is to have in writing, for parsing purposes, all the steps that would be performed for real when a build of the same switch-arguments is invoked (ideally without running anything but sometimes things run, that's up to "make" and how its targets are written, out of our control).
The goal of the "targets" phase is to identify all the targets to display them in a list. Do you see any targets missing or values that are not targets being included in the list?
Otherwise... I am not sure what else to do to address this work item. We can't control how "make" works, only what switch-arguments we send to it.

**Comment by ashblair** [comment]
@andreeis, I hope you get this! I think make was re-making the dependency files (which are make files with rules and no recipes) without regard to the modify date because: there was a rule and recipe specifically for them in the top make file, and they were included at the bottom of the top make file (which triggers some sort of re-making procedure for each included file).  I removed the rule and moved/updated the recipe so that there is only one rule which is not called by the dependency files (the recipe calls the compiler twice now which caused a problem with the includePath, I think it chooses the last one).  Everything is parsing correctly now; the configuration cache log is big and complicated but correct.  Thanks for your response.
