### ISSUE TITLE
targets.log expose my sensitive information

### ISSUE THREAD

**Issue by tangx** [microsoft/vscode-makefile-tools#402]
Hi there, 

the `.vscode/targets.log` save my all environment variable pairs. Includes some sensitive ones.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/7335398/211515676-a52cd137-9927-441a-8131-c3204c19a1af.png">

**Comment by bobbrow** [comment]
Did you solve this issue, or is it something we need to look into?

**Comment by andreeis** [comment]
I looked at "make" switches related to "--print-data-base" since we don't need the "# environment" information when we parse targets from targets.log. I wasn't able to find a way to generate this information we need without the environment variables. So we would either delete targets.log at the end (and when users have various problems we need to diagnose ask them to generate this file instead of sharing it directly, but this is the same as dryrun.log and any other file we generate) or @tangx is it ok if this sensitive information is not generated under the .vscode subfolder? For that, just leave the default value for the setting "makefile.extensionOutputFolder" (which goes somewhere in the VSCode user directory) or if you want to see them somewhere else make sure you set it towards a path outside your workspace which is not under source control (which I imagine is the problem for you now).

**Comment by zquestz** [comment]
This leaks tons of sensitive data, huge anti pattern. PLEASE do not write env vars to a file within projects!
