### ISSUE TITLE
Case sensitive on Windows

### ISSUE THREAD

**Issue by KrestenHelstrup** [microsoft/vscode-makefile-tools#416]
hi,
Looks like the plugin is case sensitive even on windows systems which are not case sensitive. In my makefile I have something like:
C_SRC +=  \
../somefolder/somefile.c
../Main.c
The proejct compiles without any issues but intellisense is not working as expected. In the extension log I see:
Configuration for file xxx\someFolder\somefile.c was not found. CppTools will set a default configuration.
As you see the folder is someFolder with capital F and if I change the makefile to correct casing everything works as expected.

Would it be possible for the plugin to be case-insensitive on windows systems ?
Issues like these are quite hard to debug.

Thanks in advance

**Comment by andreeis** [comment]
@KrestenHelstrup , thank you for pointing this out. We have a fix which will be included in the 0.7 release.

**Comment by andreeis** [comment]
@KrestenHelstrup, a fix for this will be released with 0.7 next week but if you would like to see how this works earlier you can install one vsix from [this link](https://github.com/microsoft/vscode-makefile-tools/actions/runs/4451312188).

go to the Extensions panel on the left
click "..."
run "Install from vsix" from the context menu

Let us know if you encounter any other issues or if you have any other suggestions/recommendations in this area of functionality.

**Comment by gcampbell-msft** [comment]
Due to 0.7.0 being available with this fix, we are closing this issue, please re-open if you hit issues.

**Comment by CherryDT** [comment]
"on Windows" is an incorrect oversimplification!

As I pointed out in a comment on the PR (just wasn't sure which place was better to write this), whether case-sensitivity is enabled depends not only on the platform but also on the filesystem used (one may have mounted a Linux filesystem) and **even on which folder the file is in** because on NTFS you can enable case-sensitivity per folder (I have it enabled on my projects folder, for example, because I want to catch capitalization errors early before they crash on a Linux server later on)!
