### ISSUE TITLE
Makefile Includes break VS code build.

### ISSUE THREAD

**Issue by zachgillette** [microsoft/vscode-makefile-tools#459]
Our makefile is split up into sub make files that are included in the main makefile. When attempting to build within the IDE, it reports that the other make files that are included cannot be found, and errors out. Making from the command line works fine, even the intellisense works (except for another issue that I will make a ticket for, .inc files).

**Comment by zachgillette** [comment]
Keep in mind I'm running on a remote Amazon Linux server. The make program is in the /usr/bin/ folder, however that folder is not in the scope of the project (we have many program distributions for testing). My configuration for Make Path is simply "make," since it is included in the runtime path. In the terminal, simply typing "make" is how we make. If you want, I could ask my senior programmer if we use a specialized make file.

[extension.log](https://github.com/microsoft/vscode-makefile-tools/files/11265565/extension.log)

**Comment by andreeis** [comment]
@zachgillette , It looks from the log that you selected by mistake the target make.
"Reading current build target "make" from the workspace state."
This selection happens from the "Build Target" edit pen --> quickPick selection list in the left side C/C++ Panel UI specific for the Makefile Tools extension. We automatically detect what are the targets defined in the makefile. Unless there are bugs, if you found a "make" entry it means there is a "make" target in your makefile. But since you say you run "make" with no arguments, you don't want to define any target. You have to unset it. Currently, the only way to unset that is run from the palette the command "Makefile: Reset workspace state (for troubleshooting)".

Also, in terminal, you run the simple command "make", no arguments, but from what folder? From the same folder that you open in VSCode as root workspace?

**Comment by andreeis** [comment]
@zachgillette , you can safely ignore the Tasks Output error. It actually doesn't break anything. It is a VSCode bug: https://github.com/microsoft/vscode/issues/176670. 

Do you set "makefile.makefilePath" in your settings? Usually we add -f if you do. Please specify what is the folder you open in VSCode as workspace root. 
What is the folder when you run that command in the terminal. Do you run make -f? You mentioned you run make simple, no -f.

**Comment by zachgillette** [comment]
I run from the /source/ folder.

My current json settings:
{
    "workbench.colorTheme": "Default Dark+",
    "perltidy.additionalArguments": [
    
    ],
    "workbench.iconTheme": "material-icon-theme",
    "remote.SSH.remotePlatform": {
        "aws5.strategysystems.com": "linux",
        "dvl1.strategysystems.com": "linux"
    },
    "files.associations": {
        "*.inc": "c"
    },
    "makefile.makefilePath": "source/makefile",
    "C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools",
    "C_Cpp.loggingLevel": "Debug",
    "makefile.loggingLevel": "Debug",
    "makefile.extensionOutputFolder": "./MyOutput",
    "makefile.extensionLog": "extension.log",
    "C_Cpp.files.exclude": {

        "**/.vscode": true,
        "**/.vs": true
    },
    "makefile.ignoreDirectoryCommands": false,
}

**Comment by andreeis** [comment]
So, please confirm: in the terminal outside VSCode, you go to "> cd source" and there you run "make" simple, correct?

Then, in VSCode, you open the folder "source" as workspace root or one level above it?
To replicate as much as possible the terminal, let's open "source" as workspace root in VSCode and remove "makefile.makefilePath" setting. The extension will find the makefile automatically, because it will be in the root. Later we'll try to achieve the same with opening from a different level and using makefilePath setting again.

Also, the setting "makefile.ignoreDirectoryCommands" is meant to ignore commands like "cd", "pushd", "popd" which somnetimes are not logged completely and correctly by "make" itself and only messes up our calculations. That's why the default of that boolean setting is "true". If you make it false, make sure all those commands are properly logged in how "make" will output its activity. Also, many times we don't need to look at the commands because "make" will also report "entering" or "exiting" directory. So try that boolean setting true as well, maybe will help.

Let me know what happens now.

**Comment by zachgillette** [comment]
I cannot make source the root, as it relies on files in web/source as well. The make will never work without those files. This is how I originally opened the project and realized this.

The core file structure is files in {workspace}/source and {workspace}/web/source.
![structure](https://user-images.githubusercontent.com/113057806/233189109-674eeea1-6a65-4a85-a142-378de7a55b45.png)

**Comment by andreeis** [comment]
@zachgillette, but in terminal, you do "make" simple (no -f switch) from "source" and there is no problem with the web/source outside, correct?

Ok, let's open in VSCode one level up as you did, define makefilePath as you did.... but also define "makefile.makeDirectory": "./source". Try that. And keep "makefile.ignoreDirectoryCommands": "true" for now, unless needed to be false.

**Comment by zachgillette** [comment]
That did the trick. It now runs successfully.

**Comment by andreeis** [comment]
@zachgillette , excellent, closing the ticket. Let me know about 460 then.
