### ISSUE TITLE
IntelliSense may work only partially or not at all

### ISSUE THREAD

**Issue by lai0yu** [microsoft/vscode-makefile-tools#487]
I'm trying to use vscode + makefile + cpptools to build a linux kernel source code reading environment, after reading some documents, I wrote the following settings.json
```json
{
    "makefile.preConfigureScript": "/home/lai0yu/stm_arm_source.sh",
    "makefile.alwaysPreConfigure": true,
    "makefile.configurations": [
        {
            "name": "LinuxKerneluImage",
            "makePath": "/usr/bin/make",
            "makefilePath": "/home/lai0yu/fsmp1a/kernel/linux-stm32mp-5.4.31-r0/linux-5.4.31/Makefile",
            "makeArgs": [
                "-j4",
                "ARCH=arm",
                "uImage",
                "vmlinux",
                "LOADADDR=0xC2000040"
            ],
        }
    ],
    "C_Cpp.default.configurationProvider": "ms-vscode.makefile-tools",
    "files.associations": {
        "*.h": "c",
    }
}
```
The content of the file in /home/lai0yu/stm_arm_source.sh is as follows
```shell
#!/bin/bash
source /opt/st/stm32mp1/3.1-openstlinux-5.4-dunfell-mp1-20-06-24/environment-setup-cortexa7t2hf-neon-vfpv4-ostl-linux-gnueabi
```

As you can see, my linux kernel is based on the stm32mp157 chip, and I use the cross-compilation toolchain provided by stm company, I can make sure that the configuration path of these environments is no problem.

But the makefile tool reports some problems as belows

```shell
...
IntelliSense may work only partially or not at all.
***

*** Configuration file ".config" not found!
***

*** Please run some configurator (e.g. "make oldconfig" or

*** "make menuconfig" or "make xconfig").

***

make: *** [.config] Error 1
make: Failed to remake makefile 'include/config/auto.conf.cmd'.
make: Failed to remake makefile 'include/config/auto.conf'.

scripts/mod/.devicetable-offsets.s.cmd:1: *** missing separator.  Stop.

make: *** [prepare0] Error 2


You can see the detailed dry-run output at /home/lai0yu/.vscode-server/data/User/workspaceStorage/fee1b83933360fdbf955fb086c58f6b8/ms-vscode.makefile-tools/dryrun.log
...

The compiler args parser script '/tmp/parseCompilerArgs.sh' failed with error code 1 for regions ( -Wp,-MD,scripts/genksyms/.parse.tab.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89      -I ./scripts/genksyms -c -o scripts/genksyms/parse.tab.o scripts/genksyms/parse.tab.c' > scripts/genksyms/.parse.tab.o.cmd)
Error while running the compiler args parser script '/tmp/parseCompilerArgs.sh' for regions (" -Wp,-MD,scripts/genksyms/.lex.lex.o.d -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89      -I ./scripts/genksyms -c -o scripts/genksyms/lex.lex.o scripts/genksyms/lex.lex.c' > scripts/genksyms/.lex.lex.o.cmd)": "/bin/bash: -c: line 0: unexpected EOF while looking for matching `''
/bin/bash: -c: line 1: syntax error: unexpected end of file
"
```

Here is the full relevant file
output
https://drive.google.com/file/d/1YIHIxcGDonYhHip23WFGZ2DZfTigHriU/view?usp=sharing

dryrun.log
https://drive.google.com/file/d/1cVQj1wvG7kTMHyiuFu-zuYXqEPtXhgJT/view?usp=sharing

target.log
https://drive.google.com/file/d/1I7pr1YhxQ4BvtLTUJ38zixvr5hofqouO/view?usp=sharing

**Comment by andreeis** [comment]
@lai0yu , what is the command line that works if you type it in your usual developer terminal outside VSCode?
I have seen the "Configuration file ".config" not found!" error when I was playing with linux kernel and that message is not coming from the extension. It comes from the linux kernel build system. I am not an expert in how to set up that repository but I managed to set up some basic components before. That error is caused by something wrong in the user setup.

As soon as you have a set of steps that work in the terminal then we can look at what Makefile Tools does differently.

We did not have time actually clone and try the exact files you mention but until we do maybe we find the issue while discussing possibilities on this issue link.

So, give us how the commands that lead to successful build look like (try them end to end in a separate terminal).

Then set the following settings in .vscode/settings.json:

"makefile.loggingLevel": "Debug",
"makefile.extensionOutputFolder": "./MyOutputFolder",
"makefile.extensionLog": "extension.log".

Reload linux kernel in VSCode, let it configure (see in the output channel something like "Configure finished"). And send to us these files from MyOutputFolder: dryrun.log and extension.log.
