### ISSUE TITLE
Changing integrated terminal breaks build commands

### ISSUE THREAD

**Issue by ingarpedersen** [microsoft/vscode-makefile-tools#527]
I have changed the integrated terminal to cmder. After I made this change makefile tools build target command fails:
```
 *  Executing task: ""E:\Proj\testproj\lib\make.exe" "all"" 

'D:\Program' is not recognized as an internal or external command,
operable program or batch file.

E:\Proj\testproj\lib>
```

If I switch back to command prompt as terminal build works just fine. If I run "make all" in cmder it builds just fine.

So it appears makefile tools picks up some strange settings when using cmder as integrated terminal.
The makefile tools output does not contain an error, the last 3 lines are:
```
Executing task: "Makefile Tools Build Task" with quoting style "Strong"
 command name: E:\Proj\testproj\lib\make.exe
 command args all
```
And it is stuck there until I cancel the build using the cancel button in the popup window.
I have enabled the other log file options, but nothing is written to them.

Makefile tools: v0.7.0
VS Code: 1.84.1

Possibly related issues:
https://github.com/microsoft/vscode-makefile-tools/issues/493
https://github.com/microsoft/vscode-makefile-tools/issues/481
https://github.com/microsoft/vscode-makefile-tools/issues/390

**Comment by gcampbell-msft** [comment]
@ingarpedersen Could you please provide a minimal repro project for us to investigate this with? 

It seems like you might be right that something about the environment, or possibly our string escaping in other terminals, isn't working. However, since the other logging options didn't help, we'll likely need to be able to reproduce this ourselves to investigate.

Also, do you happen to know where the "D\Program" is coming from? Is that something that might be coming from our extension? Or is that maybe coming from a makefile or project setting of yours?

Any information and repro project that you can provide would help us investigate this. Thanks!

**Comment by ingarpedersen** [comment]
I have search through the project several time scanning for any reference to D: and/or Program without finding anything.
I do see that if I run a "Make configure" the dry run completes without errors, so apparently, this only happens with a make all.

I have also made a new project, and stripped the makefile down to:
```
    all: Makefile
	@echo "Making all"
```	

make all in the terminal still works fine, but trying to build with the makefile tools gives the same error as described above, so it would seem the issue is not in any of my files, it has to come from somewhere else.

**Comment by gcampbell-msft** [comment]
@ingarpedersen Ahh, this is very useful information! This may have something to do with how we handle our paths, we may need to add quotes around the path we get to make sure that it's properly handled. Thanks for the additional information.

**Comment by gcampbell-msft** [comment]
@ingarpedersen To help me investigate this, could you provide a repro sample? Currently I don't believe we necessarily support modifying the terminal (as I've mentioned in the other bugs referenced), but it may be that we have a small amount of support. The easiest way to tell would be for you to create a repro and share it with me so that I can know the **exact** scenario that you're hitting. 

Thanks!

**Comment by ingarpedersen** [comment]
Should be fairly easy to reproduce. This is my list of profiles from the settings.json:
```
    "terminal.integrated.profiles.windows": {
        "Cmder": {
            "name": "Cmder",
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": ["/k", "D:\\\"Program Files\"\\cmder\\vendor\\bin\\vscode_init.cmd"],
            "icon": "terminal-cmd",
            "color": "terminal.ansiGreen"
        },
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        }
    },
```
Selecting "Cmder" as terminal, and not escaping the path in args, like in my settings above, triggers the issue. I have not tested if the same is the case if the path contains space. It could be that it only affect args...(?) 

If you want me to send you more let me know exactly what you need.

**Comment by gcampbell-msft** [comment]
@ingarpedersen If you add `\"` before and after the `${env:cmder-root}`, does this fix your issue?

**Comment by gcampbell-msft** [comment]
Either way, I have tested this with your settings.json setting from this comment: https://github.com/microsoft/vscode-makefile-tools/issues/527#issuecomment-1841476068, and I also tested by adding a reference to cmder-root to the "Command Prompt" profile, and it also fails there. Also, I found these two links: https://github.com/Microsoft/vscode/issues/36733, https://stackoverflow.com/questions/67171114/vscode-shell-task-escaping-single-quotes, and it seems like the issue is actually in how VSCode interprets it's variables. Hopefully the stack overflow link can help you workaround this? 

Let me know if these suggestions helped at all!

**Comment by ingarpedersen** [comment]
Adding \" before and after `${env:cmder-root}` does not appear to work. I think I'll stick with an escaped fixed path, which does work. I tried a couple of the suggestions from the SO link, but could not get those to work either, but did not spend to much time on it since I do have something that does work.

From https://github.com/microsoft/vscode/issues/36733 it would appear that escaping of arguments is left to the user.

Thanks.

**Comment by gcampbell-msft** [comment]
@ingarpedersen Thanks for the follow up. Since it seems that vscode leaves the escaping of arguments to the user, I'll close this issue. 

There are other issues on this repo that we're tracking for adding support for using the terminal profiles for things like build. Thanks!
