### ISSUE TITLE
Terminal momentarily blanks during run

### ISSUE THREAD

**Issue by codefrogs** [microsoft/vscode-makefile-tools#578]
The terminal window blanks and redraws during a run.
Although this is momentary, it's somewhat distracting, especially when performing multiple runs sequentially, thus making it harder to keep track of changes in output, i.e. You have to identify the previous output text, then identify the latest / new output text. 
This of course adds to the user's cognitive load. 

To reproduce:
Run an application using the 'run' icon.
Terminal refreshes by blanking, then redrawing content, and then outputs the application text.
Example:
Pre-run:
![01-run](https://github.com/microsoft/vscode-makefile-tools/assets/79409528/0fc56b5a-d7d1-4905-a98e-6bc0f17ae888)
Blanks:
![02-run](https://github.com/microsoft/vscode-makefile-tools/assets/79409528/d4e6343d-9d73-4f95-ad19-15bbed4dd27d)
Post run:
![03-run](https://github.com/microsoft/vscode-makefile-tools/assets/79409528/c56b3eca-4ad2-4984-9b2a-ce149736f139)

**Comment by gcampbell-msft** [comment]
@codefrogs Thanks for posting this, I've labeled it as a bug and placed in on the backlog. Thanks!

**Comment by gcampbell-msft** [comment]
@codefrogs Revisiting this, my initial investigation finds that we don't have control over how the terminal draws itself. Do you have a repro project that I could investigate with? I could test yours specifically, otherwise, I believe this is a general vscode implementation that we don't have control over. Thanks!
