### ISSUE TITLE
Drastically increases formatting time upon saving a file

### ISSUE THREAD

**Issue by karans765** [microsoft/vscode-makefile-tools#594]
Type: <b>Bug</b>

Drastically increases formatting time upon saving

Extension version: 0.9.10
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:14:32.757Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.85GB free)|
|Process Argv|--crash-reporter-id 66b97fca-25e1-4892-ad19-893ae6481d3b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
showvideoc:31016891
chatpanelc:31048052
dsvsc021:30996838
01bff139:31013167
pythoncenvptcf:31049071
a69g1124:31046351
pythonprt:31047983
dwnewjupytercf:31046870
fa862199:31048878

```

</details>

**Comment by Yingzi1234** [comment]
@karans765 We are trying to reproduce your problem, could you provide some information below in order to better solve the problem??
1. Could you provide us with the detailed steps for reproduction?
2. In addition to the VS Code version and OS version you have provided, you may also need to know your extension configuration. In particular, regarding any custom configuration of the Makefile Tools extension.
3. If possible, provide the sample code snippet or file that is causing the problem. This will give a clearer picture of the nature of the problem
4. If you are experiencing this problem in a specific project, additional information about the project's environment, such as project structure, dependencies, etc., can also be provided

By providing this information, developers can better understand the problem and try to reproduce it in their environment, making it easier to diagnose and resolve your issue, thank you!

**Comment by gcampbell-msft** [comment]
@sean-mcmanus @Colengms I seem to recall that there have been issues related to this in the past and we ended up finding out that it was with the c/c++ extension, could you weigh in here? Or correct me if I'm remembering incorrectly

**Comment by sean-mcmanus** [comment]
@gcampbell-msft Yeah, it certainly could be caused by cpptools. We have https://github.com/microsoft/vscode-cpptools/issues/12082 (if "editor.formatOnSaveMode": "modificationsIfAvailable is used) and https://github.com/microsoft/vscode-cpptools/issues/6156 (if IntelliSense is blocking the formatting, you can verify this by checking if formatting is fast if there's no pending IntelliSense operation). We probably need more info from the user to confirm which issue/extension is the cause.

**Comment by gcampbell-msft** [comment]
@karans765 Could you provide more info and maybe test different settings for the ones that @sean-mcmanus pointed out? Thanks.
