### ISSUE TITLE
Difficulties configuring extension

### ISSUE THREAD

**Issue by nschmeller** [microsoft/vscode-makefile-tools#71]
I downloaded the .vsix file from the latest release and installed with the "Install from VSIX" command. I got the prompt saying "Makefile Tools would like to configure IntelliSense for this folder.", and I clicked on Allow. I double checked that Makefile Tools was active by running the "C/C++: Change Configuration Provider" command, it had (active) at the right. 

When I open a C file, I get a red squiggly on the first character of the file, saying `command-line error: language modes specified are incompatible C/C++(1027)`.  Additionally, in the Output tab of the terminal labeled makefile-tools, I got this log

```
Logging level: Normal
Provided extension output folder does not exist: /u/nbs/project5/.vscode.
Switching to default: ./.vscode.
Dropping various extension output files at /u/nbs/project5/.vscode
Configurations cached at /u/nbs/project5/.vscode/configurationCache.log
No path to the makefile is defined in the settings file
Always pre-configure: false
Dry-run switches: --always-make,--keep-going,--print-directory
No current configuration is defined in the workspace state. Assuming 'Default'.
No target defined in the workspace state. Assuming 'Default'.
No current launch configuration is set in the workspace state.
Default launch configuration: MIMode = undefined,
                    miDebuggerPath = undefined,
                    stopAtEntry = undefined,
                    symbolSearchPath = undefined
Configure on open: true
Configure on edit: true
Configure after command: true
Deduced command 'make ' for configuration Default
Generating configuration cache with command: make --dry-run --always-make --keep-going --print-directory
Writing the dry-run output: /u/nbs/project5/.vscode/dryrun.log
Generating dry-run elapsed time: 0.628
Preprocessing: "/u/nbs/project5/.vscode/dryrun.log"
Preprocess elapsed time: 0
Parsing for IntelliSense.
Updating the CppTools IntelliSense Configuration Provider.
Parsing dry-run output for CppTools Custom Configuration Provider.
Sending Workspace Browse Configuration: -----------------------------------
    Browse Path: /u/nbs/project5
    Standard: c11
    Compiler Path: /usr/bin/gcc
    Compiler Arguments: -o asmdefs
----------------------------------------------------------------------------
Parsing for IntelliSense elapsed time: 0.009
Parsing for launch targets.
Found the following 1 launch targets defined in the makefile: /u/nbs/project5>asmdefs()
Complete list of launch targets: /u/nbs/project5>asmdefs()
Parsing for launch targets elapsed time: 0.009
Generating parse content for build targets.
Generating targets information with command: make all --print-data-base --no-builtin-variables --no-builtin-rules --question
Writing the dry-run output: /u/nbs/project5/.vscode/targets.log
Generating dry-run elapsed time: 0.283
Parsing for build targets from: "/u/nbs/project5/.vscode/targets.log"
Found the following 45 build targets defined in the makefile: TAGS;all;asmdefs;asmdefs.o;asmsyms.h;boot;bootblock;bootblock.o;clean;createimage;createimage.o;demo;depend;dispatch.o;distclean;entry.o;image;interrupt.o;kernel;kernel.o;keyboard.o;mbox.o;memory.o;print.o;process1;process1.o;process2;process2.o;process3;process3.o;process4;process4.o;progdisk;scheduler.o;shell;shell.o;sleep.o;syslib.o;tags;th1.o;th2.o;thread.o;time.o;tlb.o;util.o
Complete list of build targets: TAGS;all;asmdefs;asmdefs.o;asmsyms.h;boot;bootblock;bootblock.o;clean;createimage;createimage.o;demo;depend;dispatch.o;distclean;entry.o;image;interrupt.o;kernel;kernel.o;keyboard.o;mbox.o;memory.o;print.o;process1;process1.o;process2;process2.o;process3;process3.o;process4;process4.o;progdisk;scheduler.o;shell;shell.o;sleep.o;syslib.o;tags;th1.o;th2.o;thread.o;time.o;tlb.o;util.o
Parsing build targets elapsed time: 0.099
Configure finished. The status for all the subphases that ran:
loadFromCache: return code = -3, elapsed time = 0
generateParseContent: return code = 0, elapsed time = 0.628
preprocessParseContent: return code = 0, elapsed time = 0
parseIntelliSense: return code = 0, elapsed time = 0.009
parseLaunch: return code = 0, elapsed time = 0.009
dryrunTargets: return code = 1, elapsed time = 0.283
parseTargets: return code = 0, elapsed time = 0.099
Configure succeeded.
Configure elapsed time: 1.321
Configuration for file /u/nbs/project5/memory.c was not found. CppTools will set a default configuration.
Configuration for file /u/nbs/project5/memory.c was not found. CppTools will set a default configuration.
Configuration for file /u/nbs/project5/memory.c was not found. CppTools will set a default configuration.
Configuration for file /u/nbs/project5/interrupt.c was not found. CppTools will set a default configuration.
Configuration for file /u/nbs/project5/kernel.c was not found. CppTools will set a default configuration.
Configuration for file /u/nbs/project5/memory.h was not found. CppTools will set a default configuration.
Configuration for file /u/nbs/project5/memory.c was not found. CppTools will set a default configuration.
```

I'm not entirely sure what is going wrong here, but hopefully this is helpful! Please let me know if I'm doing something wrong!

Here's some more information about my system (note that I'm using the remote SSH extension to ssh from my Mac to a Linux computer):

Extension version: 0.1.1
VS Code version: Code 1.51.1 (e5a624b788d92b8d34d1392e4c4d9789406efe8f, 2020-11-11T01:11:34.018Z)
OS version: Darwin x64 20.1.0
Remote OS version: Linux x64 3.10.0-1127.13.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 3, 3|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 5bf3bb8f-57b1-4dda-9c7c-de15247d23d0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: courselab|
|OS|Linux x64 3.10.0-1127.13.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz (64 x 3053)|
|Memory (System)|125.47GB (35.43GB free)|
|VM|0%|
</details>

**Comment by andreeis** [comment]
We released Makefile Tools 0.1.2. Try it out and let us know if you encounter any problems.

I finally saw the incompatible language modes squiggle while testing a different repo and in that case it happened for a c/c++ file that was not part of the last make build so the extension did not parse any compilation command for that source. Probably the C/C++ extension defaulted to some language mode which was incompatible with the language mode that the extension detected for the whole project browse configuration. If you see this next time, search that source file name in .vscode/dryrun.log and also in the output channel (verbose or debug loggingLevel). If you don't see the file in dryrun.log, check the make command that the extension calculated (first line of dryrun.log). If the command is correct fix your build to include the file, otherwise open a bug for us.

**Comment by MiguelGuthridge** [comment]
I seem to be getting the same error on a project, but only for one .c/.h pair in the project. It was originally all my open files, but the others fixed themselves after I restarted VS Code. I'm honestly not sure what's going on... it could just be another symptom of my laptop's dying hard drive or something. If there's any info that I can include to help out with diagnosing the issue I'll gladly provide it (although I can't give source files because university will murder me).

**Comment by Lutra-Fs** [comment]
the same issue, and looks like we are doing the same work. is the file Girvan Newman? @MiguelGuthridge

**Comment by andreeis** [comment]
@MiguelGuthridge and @Lutra-Fs, it may happen for these squiggles to be inconsistent. The bug in the Makefile Tools extension would be consistent (let's say providing wrong info or none for a file) but CppTools sometimes is able to deduce defaults also when loading other source files around.

Set debugging loggingLevel for both Makefile Tools and CppTools in your .vscode/settings.json to be ready:
"makefile.loggingLevel": "Debug",
"C_Cpp.loggingLevel": "Debug"

Whenever the squiggles happen again, pause your activity, run the command "C/C++: Log Diagnostics" and copy paste for us the content of 3 output channels: "Makefile Tools", "C/C++" and "C/C++ Diagnostics".

Also we will release Makefile 0.2.1 soon with many fixes with IntelliSense impact. I have one getting close and I'll let you know when you can try a custom vsix even before 0.2.1 is out.

**Comment by MiguelGuthridge** [comment]
@andreeis thanks! I'll keep an eye out for the next time I can reproduce it. It seems like I was able to stop the issue by building the project. The error would only happen for files that hadn't been included in a build yet. I might do some experimentation to see if it requires the project to be made using the extension or whether it is also fixed by running `make all`. This looks like it's a very interesting piece of the puzzle and might help with narrowing down the issues a lot.

**Comment by andreeis** [comment]
Oh, that is a by design scenario. Depending on how a makefile is set up, the extension may not be able to gather all information. Always look in .vscode/dryrun.log to see if a file with missing or bad IntelliSense is present in a compilation command in there. If it's missing, then the extension can't do much.

There are several tricky scenarios when the extension can't know all that it needs. They are described in the repository at docs/troubleshooting.md. Have a look just to be aware of all that can happen and to learn many valuable workarounds.

**Comment by MiguelGuthridge** [comment]
Oh cool that does make sense... In that case, would it be possible to actually have a specific message for that to let the user know that they just need to make the file and it'll be able to process things properly then? I can imagine a ton of users getting just as confused as me when they encounter this particular issue, and being sent on a wild goose chase trying to find the solution in the C/C++ extension (since the current error looks like it's coming from there). Being honest I only found this thread since I've learnt to check for makefile tools things whenever I run into issues first. Basically some kind of warning notification, or a more descriptive error message would be helpful I think.

**Comment by andreeis** [comment]
You are right. First, let me know when that happens again (or make it happen, add a new file :) that won't be picked up by the dry-run build), do you see a message in the output channel mentioning that "Configuration for file [your file] was not found. CppTools will set a default configuration."

We can make the output channel visible with every such message. Would you prefer a popup on the bottom right side? We thought such popup may be too annoying because depending on projects setup and developers workflows it can happen often. So we thought to only log a message. But indeed, I think we can make the output channel visible again when this message is printed, in case the user is viewing problems or terminal or debug console in that moment.

**Comment by MiguelGuthridge** [comment]
A pop-up in the bottom right could be quite intrusive for some people actually. I think the best option would be to add something to the problems list for that file explaining why it isn't getting intellisense and why it has the 1027 error. That way people would see it when they saw the existing error and would be pointed in the right direction for solving it.

**Comment by andreeis** [comment]
Thank you for the suggestion. We will make sure to consider it when we implement problems and matchers support: https://github.com/microsoft/vscode-makefile-tools/issues/7.

**Comment by MiguelGuthridge** [comment]
That sounds great! I'm so keen to see how it pans out, and thanks so much for the consideration of my ideas!
