### ISSUE TITLE
Make not detected in path

### ISSUE THREAD

**Issue by KrestenHelstrup** [microsoft/vscode-makefile-tools#89]
If I remove the following from settings.json:
"makefile.makePath": "C:/ARMTC/ARMGCC/bin/make.exe",
I keep getting this error from the extension:
![MakeIssue](https://user-images.githubusercontent.com/74759135/105852408-bc398300-5fe4-11eb-8d8f-d19d0ebdffa7.PNG)
But make is in path for sure, the project even builds without the line.

Running VSCode on windows.

**Comment by KrestenHelstrup** [comment]
When is 1.0.0 expected to be released ?

**Comment by bobbrow** [comment]
When we named it 1.0, we were actually just referring to the first release to the VS Code Extension Marketplace.  The actual version number of our first release will be 0.2.0 since we still consider the extension to be in "preview" stage.  We are finishing up some documentation and plan to publish to the Marketplace very soon (as early as next week).
